// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.app.models;

import com.azure.core.annotation.Fluent;
import com.azure.json.JsonReader;
import com.azure.json.JsonToken;
import com.azure.json.JsonWriter;
import java.io.IOException;
import java.util.List;

/**
 * The ActionSuppressedDetails model.
 */
@Fluent
public final class ActionSuppressedDetails extends BaseDetails {
    /*
     * Type of modification details
     */
    private AlertModificationType type = AlertModificationType.ACTIONS_SUPPRESSED;

    /*
     * List of suppression action rules
     */
    private List<String> suppressionActionRules;

    /*
     * List of suppressed action groups
     */
    private List<TriggeredRule> suppressedActionGroups;

    /**
     * Creates an instance of ActionSuppressedDetails class.
     */
    public ActionSuppressedDetails() {
    }

    /**
     * Get the type property: Type of modification details.
     * 
     * @return the type value.
     */
    @Override
    public AlertModificationType type() {
        return this.type;
    }

    /**
     * Get the suppressionActionRules property: List of suppression action rules.
     * 
     * @return the suppressionActionRules value.
     */
    public List<String> suppressionActionRules() {
        return this.suppressionActionRules;
    }

    /**
     * Set the suppressionActionRules property: List of suppression action rules.
     * 
     * @param suppressionActionRules the suppressionActionRules value to set.
     * @return the ActionSuppressedDetails object itself.
     */
    public ActionSuppressedDetails withSuppressionActionRules(List<String> suppressionActionRules) {
        this.suppressionActionRules = suppressionActionRules;
        return this;
    }

    /**
     * Get the suppressedActionGroups property: List of suppressed action groups.
     * 
     * @return the suppressedActionGroups value.
     */
    public List<TriggeredRule> suppressedActionGroups() {
        return this.suppressedActionGroups;
    }

    /**
     * Set the suppressedActionGroups property: List of suppressed action groups.
     * 
     * @param suppressedActionGroups the suppressedActionGroups value to set.
     * @return the ActionSuppressedDetails object itself.
     */
    public ActionSuppressedDetails withSuppressedActionGroups(List<TriggeredRule> suppressedActionGroups) {
        this.suppressedActionGroups = suppressedActionGroups;
        return this;
    }

    /**
     * Validates the instance.
     * 
     * @throws IllegalArgumentException thrown if the instance is not valid.
     */
    @Override
    public void validate() {
        if (suppressedActionGroups() != null) {
            suppressedActionGroups().forEach(e -> e.validate());
        }
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public JsonWriter toJson(JsonWriter jsonWriter) throws IOException {
        jsonWriter.writeStartObject();
        jsonWriter.writeStringField("type", this.type == null ? null : this.type.toString());
        jsonWriter.writeArrayField("suppressionActionRules", this.suppressionActionRules,
            (writer, element) -> writer.writeString(element));
        jsonWriter.writeArrayField("suppressedActionGroups", this.suppressedActionGroups,
            (writer, element) -> writer.writeJson(element));
        return jsonWriter.writeEndObject();
    }

    /**
     * Reads an instance of ActionSuppressedDetails from the JsonReader.
     * 
     * @param jsonReader The JsonReader being read.
     * @return An instance of ActionSuppressedDetails if the JsonReader was pointing to an instance of it, or null if it
     * was pointing to JSON null.
     * @throws IOException If an error occurs while reading the ActionSuppressedDetails.
     */
    public static ActionSuppressedDetails fromJson(JsonReader jsonReader) throws IOException {
        return jsonReader.readObject(reader -> {
            ActionSuppressedDetails deserializedActionSuppressedDetails = new ActionSuppressedDetails();
            while (reader.nextToken() != JsonToken.END_OBJECT) {
                String fieldName = reader.getFieldName();
                reader.nextToken();

                if ("type".equals(fieldName)) {
                    deserializedActionSuppressedDetails.type = AlertModificationType.fromString(reader.getString());
                } else if ("suppressionActionRules".equals(fieldName)) {
                    List<String> suppressionActionRules = reader.readArray(reader1 -> reader1.getString());
                    deserializedActionSuppressedDetails.suppressionActionRules = suppressionActionRules;
                } else if ("suppressedActionGroups".equals(fieldName)) {
                    List<TriggeredRule> suppressedActionGroups
                        = reader.readArray(reader1 -> TriggeredRule.fromJson(reader1));
                    deserializedActionSuppressedDetails.suppressedActionGroups = suppressedActionGroups;
                } else {
                    reader.skipChildren();
                }
            }

            return deserializedActionSuppressedDetails;
        });
    }
}
