// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.app.models;

import com.azure.core.annotation.Fluent;
import com.azure.json.JsonReader;
import com.azure.json.JsonToken;
import com.azure.json.JsonWriter;
import java.io.IOException;

/**
 * The ActionTriggeredDetails model.
 */
@Fluent
public final class ActionTriggeredDetails extends BaseDetails {
    /*
     * Type of modification details
     */
    private AlertModificationType type = AlertModificationType.ACTIONS_TRIGGERED;

    /*
     * The action group that was triggered
     */
    private TriggeredRule actionGroup;

    /*
     * The result of the notification delivery
     */
    private NotificationResult notificationResult;

    /**
     * Creates an instance of ActionTriggeredDetails class.
     */
    public ActionTriggeredDetails() {
    }

    /**
     * Get the type property: Type of modification details.
     * 
     * @return the type value.
     */
    @Override
    public AlertModificationType type() {
        return this.type;
    }

    /**
     * Get the actionGroup property: The action group that was triggered.
     * 
     * @return the actionGroup value.
     */
    public TriggeredRule actionGroup() {
        return this.actionGroup;
    }

    /**
     * Set the actionGroup property: The action group that was triggered.
     * 
     * @param actionGroup the actionGroup value to set.
     * @return the ActionTriggeredDetails object itself.
     */
    public ActionTriggeredDetails withActionGroup(TriggeredRule actionGroup) {
        this.actionGroup = actionGroup;
        return this;
    }

    /**
     * Get the notificationResult property: The result of the notification delivery.
     * 
     * @return the notificationResult value.
     */
    public NotificationResult notificationResult() {
        return this.notificationResult;
    }

    /**
     * Set the notificationResult property: The result of the notification delivery.
     * 
     * @param notificationResult the notificationResult value to set.
     * @return the ActionTriggeredDetails object itself.
     */
    public ActionTriggeredDetails withNotificationResult(NotificationResult notificationResult) {
        this.notificationResult = notificationResult;
        return this;
    }

    /**
     * Validates the instance.
     * 
     * @throws IllegalArgumentException thrown if the instance is not valid.
     */
    @Override
    public void validate() {
        if (actionGroup() != null) {
            actionGroup().validate();
        }
        if (notificationResult() != null) {
            notificationResult().validate();
        }
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public JsonWriter toJson(JsonWriter jsonWriter) throws IOException {
        jsonWriter.writeStartObject();
        jsonWriter.writeStringField("type", this.type == null ? null : this.type.toString());
        jsonWriter.writeJsonField("actionGroup", this.actionGroup);
        jsonWriter.writeJsonField("notificationResult", this.notificationResult);
        return jsonWriter.writeEndObject();
    }

    /**
     * Reads an instance of ActionTriggeredDetails from the JsonReader.
     * 
     * @param jsonReader The JsonReader being read.
     * @return An instance of ActionTriggeredDetails if the JsonReader was pointing to an instance of it, or null if it
     * was pointing to JSON null.
     * @throws IOException If an error occurs while reading the ActionTriggeredDetails.
     */
    public static ActionTriggeredDetails fromJson(JsonReader jsonReader) throws IOException {
        return jsonReader.readObject(reader -> {
            ActionTriggeredDetails deserializedActionTriggeredDetails = new ActionTriggeredDetails();
            while (reader.nextToken() != JsonToken.END_OBJECT) {
                String fieldName = reader.getFieldName();
                reader.nextToken();

                if ("type".equals(fieldName)) {
                    deserializedActionTriggeredDetails.type = AlertModificationType.fromString(reader.getString());
                } else if ("actionGroup".equals(fieldName)) {
                    deserializedActionTriggeredDetails.actionGroup = TriggeredRule.fromJson(reader);
                } else if ("notificationResult".equals(fieldName)) {
                    deserializedActionTriggeredDetails.notificationResult = NotificationResult.fromJson(reader);
                } else {
                    reader.skipChildren();
                }
            }

            return deserializedActionTriggeredDetails;
        });
    }
}
