// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.app.models;

import com.azure.core.annotation.Fluent;
import com.azure.json.JsonReader;
import com.azure.json.JsonSerializable;
import com.azure.json.JsonToken;
import com.azure.json.JsonWriter;
import java.io.IOException;
import java.util.List;

/**
 * Properties of the alert enrichment item.
 */
@Fluent
public final class AlertEnrichmentProperties implements JsonSerializable<AlertEnrichmentProperties> {
    /*
     * Unique Id (GUID) of the alert for which the enrichments are being retrieved.
     */
    private String alertId;

    /*
     * Enrichment details
     */
    private List<AlertEnrichmentItem> enrichments;

    /**
     * Creates an instance of AlertEnrichmentProperties class.
     */
    public AlertEnrichmentProperties() {
    }

    /**
     * Get the alertId property: Unique Id (GUID) of the alert for which the enrichments are being retrieved.
     * 
     * @return the alertId value.
     */
    public String alertId() {
        return this.alertId;
    }

    /**
     * Get the enrichments property: Enrichment details.
     * 
     * @return the enrichments value.
     */
    public List<AlertEnrichmentItem> enrichments() {
        return this.enrichments;
    }

    /**
     * Set the enrichments property: Enrichment details.
     * 
     * @param enrichments the enrichments value to set.
     * @return the AlertEnrichmentProperties object itself.
     */
    public AlertEnrichmentProperties withEnrichments(List<AlertEnrichmentItem> enrichments) {
        this.enrichments = enrichments;
        return this;
    }

    /**
     * Validates the instance.
     * 
     * @throws IllegalArgumentException thrown if the instance is not valid.
     */
    public void validate() {
        if (enrichments() != null) {
            enrichments().forEach(e -> e.validate());
        }
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public JsonWriter toJson(JsonWriter jsonWriter) throws IOException {
        jsonWriter.writeStartObject();
        jsonWriter.writeArrayField("enrichments", this.enrichments, (writer, element) -> writer.writeJson(element));
        return jsonWriter.writeEndObject();
    }

    /**
     * Reads an instance of AlertEnrichmentProperties from the JsonReader.
     * 
     * @param jsonReader The JsonReader being read.
     * @return An instance of AlertEnrichmentProperties if the JsonReader was pointing to an instance of it, or null if
     * it was pointing to JSON null.
     * @throws IOException If an error occurs while reading the AlertEnrichmentProperties.
     */
    public static AlertEnrichmentProperties fromJson(JsonReader jsonReader) throws IOException {
        return jsonReader.readObject(reader -> {
            AlertEnrichmentProperties deserializedAlertEnrichmentProperties = new AlertEnrichmentProperties();
            while (reader.nextToken() != JsonToken.END_OBJECT) {
                String fieldName = reader.getFieldName();
                reader.nextToken();

                if ("alertId".equals(fieldName)) {
                    deserializedAlertEnrichmentProperties.alertId = reader.getString();
                } else if ("enrichments".equals(fieldName)) {
                    List<AlertEnrichmentItem> enrichments
                        = reader.readArray(reader1 -> AlertEnrichmentItem.fromJson(reader1));
                    deserializedAlertEnrichmentProperties.enrichments = enrichments;
                } else {
                    reader.skipChildren();
                }
            }

            return deserializedAlertEnrichmentProperties;
        });
    }
}
