// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.app.models;

import com.azure.app.fluent.models.AlertEnrichmentResponseInner;
import com.azure.core.annotation.Fluent;
import com.azure.json.JsonReader;
import com.azure.json.JsonSerializable;
import com.azure.json.JsonToken;
import com.azure.json.JsonWriter;
import java.io.IOException;
import java.util.List;

/**
 * List the alert's enrichments.
 */
@Fluent
public final class AlertEnrichmentsList implements JsonSerializable<AlertEnrichmentsList> {
    /*
     * List the alert's enrichments
     */
    private List<AlertEnrichmentResponseInner> value;

    /*
     * Request URL that can be used to query next page.
     */
    private String nextLink;

    /**
     * Creates an instance of AlertEnrichmentsList class.
     */
    public AlertEnrichmentsList() {
    }

    /**
     * Get the value property: List the alert's enrichments.
     * 
     * @return the value value.
     */
    public List<AlertEnrichmentResponseInner> value() {
        return this.value;
    }

    /**
     * Set the value property: List the alert's enrichments.
     * 
     * @param value the value value to set.
     * @return the AlertEnrichmentsList object itself.
     */
    public AlertEnrichmentsList withValue(List<AlertEnrichmentResponseInner> value) {
        this.value = value;
        return this;
    }

    /**
     * Get the nextLink property: Request URL that can be used to query next page.
     * 
     * @return the nextLink value.
     */
    public String nextLink() {
        return this.nextLink;
    }

    /**
     * Set the nextLink property: Request URL that can be used to query next page.
     * 
     * @param nextLink the nextLink value to set.
     * @return the AlertEnrichmentsList object itself.
     */
    public AlertEnrichmentsList withNextLink(String nextLink) {
        this.nextLink = nextLink;
        return this;
    }

    /**
     * Validates the instance.
     * 
     * @throws IllegalArgumentException thrown if the instance is not valid.
     */
    public void validate() {
        if (value() != null) {
            value().forEach(e -> e.validate());
        }
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public JsonWriter toJson(JsonWriter jsonWriter) throws IOException {
        jsonWriter.writeStartObject();
        jsonWriter.writeArrayField("value", this.value, (writer, element) -> writer.writeJson(element));
        jsonWriter.writeStringField("nextLink", this.nextLink);
        return jsonWriter.writeEndObject();
    }

    /**
     * Reads an instance of AlertEnrichmentsList from the JsonReader.
     * 
     * @param jsonReader The JsonReader being read.
     * @return An instance of AlertEnrichmentsList if the JsonReader was pointing to an instance of it, or null if it
     * was pointing to JSON null.
     * @throws IOException If an error occurs while reading the AlertEnrichmentsList.
     */
    public static AlertEnrichmentsList fromJson(JsonReader jsonReader) throws IOException {
        return jsonReader.readObject(reader -> {
            AlertEnrichmentsList deserializedAlertEnrichmentsList = new AlertEnrichmentsList();
            while (reader.nextToken() != JsonToken.END_OBJECT) {
                String fieldName = reader.getFieldName();
                reader.nextToken();

                if ("value".equals(fieldName)) {
                    List<AlertEnrichmentResponseInner> value
                        = reader.readArray(reader1 -> AlertEnrichmentResponseInner.fromJson(reader1));
                    deserializedAlertEnrichmentsList.value = value;
                } else if ("nextLink".equals(fieldName)) {
                    deserializedAlertEnrichmentsList.nextLink = reader.getString();
                } else {
                    reader.skipChildren();
                }
            }

            return deserializedAlertEnrichmentsList;
        });
    }
}
