// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.app.models;

import com.azure.core.annotation.Fluent;
import com.azure.core.util.logging.ClientLogger;
import com.azure.json.JsonReader;
import com.azure.json.JsonToken;
import com.azure.json.JsonWriter;
import java.io.IOException;
import java.util.List;

/**
 * Prometheus enrichment object.
 */
@Fluent
public class PrometheusEnrichmentItem extends AlertEnrichmentItem {
    /*
     * The enrichment type.
     */
    private Type type = Type.fromString("PrometheusEnrichmentItem");

    /*
     * Link to Prometheus query API (Url format).
     */
    private String linkToApi;

    /*
     * An array of the azure monitor workspace resource ids.
     */
    private List<String> datasources;

    /*
     * Partial link to the Grafana explore API.
     */
    private String grafanaExplorePath;

    /*
     * The Prometheus expression query.
     */
    private String query;

    /**
     * Creates an instance of PrometheusEnrichmentItem class.
     */
    public PrometheusEnrichmentItem() {
    }

    /**
     * Get the type property: The enrichment type.
     * 
     * @return the type value.
     */
    @Override
    public Type type() {
        return this.type;
    }

    /**
     * Get the linkToApi property: Link to Prometheus query API (Url format).
     * 
     * @return the linkToApi value.
     */
    public String linkToApi() {
        return this.linkToApi;
    }

    /**
     * Set the linkToApi property: Link to Prometheus query API (Url format).
     * 
     * @param linkToApi the linkToApi value to set.
     * @return the PrometheusEnrichmentItem object itself.
     */
    public PrometheusEnrichmentItem withLinkToApi(String linkToApi) {
        this.linkToApi = linkToApi;
        return this;
    }

    /**
     * Get the datasources property: An array of the azure monitor workspace resource ids.
     * 
     * @return the datasources value.
     */
    public List<String> datasources() {
        return this.datasources;
    }

    /**
     * Set the datasources property: An array of the azure monitor workspace resource ids.
     * 
     * @param datasources the datasources value to set.
     * @return the PrometheusEnrichmentItem object itself.
     */
    public PrometheusEnrichmentItem withDatasources(List<String> datasources) {
        this.datasources = datasources;
        return this;
    }

    /**
     * Get the grafanaExplorePath property: Partial link to the Grafana explore API.
     * 
     * @return the grafanaExplorePath value.
     */
    public String grafanaExplorePath() {
        return this.grafanaExplorePath;
    }

    /**
     * Set the grafanaExplorePath property: Partial link to the Grafana explore API.
     * 
     * @param grafanaExplorePath the grafanaExplorePath value to set.
     * @return the PrometheusEnrichmentItem object itself.
     */
    public PrometheusEnrichmentItem withGrafanaExplorePath(String grafanaExplorePath) {
        this.grafanaExplorePath = grafanaExplorePath;
        return this;
    }

    /**
     * Get the query property: The Prometheus expression query.
     * 
     * @return the query value.
     */
    public String query() {
        return this.query;
    }

    /**
     * Set the query property: The Prometheus expression query.
     * 
     * @param query the query value to set.
     * @return the PrometheusEnrichmentItem object itself.
     */
    public PrometheusEnrichmentItem withQuery(String query) {
        this.query = query;
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PrometheusEnrichmentItem withTitle(String title) {
        super.withTitle(title);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PrometheusEnrichmentItem withDescription(String description) {
        super.withDescription(description);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PrometheusEnrichmentItem withStatus(Status status) {
        super.withStatus(status);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PrometheusEnrichmentItem withErrorMessage(String errorMessage) {
        super.withErrorMessage(errorMessage);
        return this;
    }

    /**
     * Validates the instance.
     * 
     * @throws IllegalArgumentException thrown if the instance is not valid.
     */
    @Override
    public void validate() {
        if (linkToApi() == null) {
            throw LOGGER.atError()
                .log(new IllegalArgumentException(
                    "Missing required property linkToApi in model PrometheusEnrichmentItem"));
        }
        if (datasources() == null) {
            throw LOGGER.atError()
                .log(new IllegalArgumentException(
                    "Missing required property datasources in model PrometheusEnrichmentItem"));
        }
        if (grafanaExplorePath() == null) {
            throw LOGGER.atError()
                .log(new IllegalArgumentException(
                    "Missing required property grafanaExplorePath in model PrometheusEnrichmentItem"));
        }
        if (query() == null) {
            throw LOGGER.atError()
                .log(new IllegalArgumentException("Missing required property query in model PrometheusEnrichmentItem"));
        }
        if (title() == null) {
            throw LOGGER.atError()
                .log(new IllegalArgumentException("Missing required property title in model PrometheusEnrichmentItem"));
        }
        if (description() == null) {
            throw LOGGER.atError()
                .log(new IllegalArgumentException(
                    "Missing required property description in model PrometheusEnrichmentItem"));
        }
        if (status() == null) {
            throw LOGGER.atError()
                .log(
                    new IllegalArgumentException("Missing required property status in model PrometheusEnrichmentItem"));
        }
    }

    private static final ClientLogger LOGGER = new ClientLogger(PrometheusEnrichmentItem.class);

    /**
     * {@inheritDoc}
     */
    @Override
    public JsonWriter toJson(JsonWriter jsonWriter) throws IOException {
        jsonWriter.writeStartObject();
        jsonWriter.writeStringField("title", title());
        jsonWriter.writeStringField("description", description());
        jsonWriter.writeStringField("status", status() == null ? null : status().toString());
        jsonWriter.writeStringField("errorMessage", errorMessage());
        jsonWriter.writeStringField("linkToApi", this.linkToApi);
        jsonWriter.writeArrayField("datasources", this.datasources, (writer, element) -> writer.writeString(element));
        jsonWriter.writeStringField("grafanaExplorePath", this.grafanaExplorePath);
        jsonWriter.writeStringField("query", this.query);
        jsonWriter.writeStringField("type", this.type == null ? null : this.type.toString());
        return jsonWriter.writeEndObject();
    }

    /**
     * Reads an instance of PrometheusEnrichmentItem from the JsonReader.
     * 
     * @param jsonReader The JsonReader being read.
     * @return An instance of PrometheusEnrichmentItem if the JsonReader was pointing to an instance of it, or null if
     * it was pointing to JSON null.
     * @throws IllegalStateException If the deserialized JSON object was missing any required properties.
     * @throws IOException If an error occurs while reading the PrometheusEnrichmentItem.
     */
    public static PrometheusEnrichmentItem fromJson(JsonReader jsonReader) throws IOException {
        return jsonReader.readObject(reader -> {
            String discriminatorValue = null;
            try (JsonReader readerToUse = reader.bufferObject()) {
                readerToUse.nextToken(); // Prepare for reading
                while (readerToUse.nextToken() != JsonToken.END_OBJECT) {
                    String fieldName = readerToUse.getFieldName();
                    readerToUse.nextToken();
                    if ("type".equals(fieldName)) {
                        discriminatorValue = readerToUse.getString();
                        break;
                    } else {
                        readerToUse.skipChildren();
                    }
                }
                // Use the discriminator value to determine which subtype should be deserialized.
                if ("PrometheusInstantQuery".equals(discriminatorValue)) {
                    return PrometheusInstantQuery.fromJson(readerToUse.reset());
                } else if ("PrometheusRangeQuery".equals(discriminatorValue)) {
                    return PrometheusRangeQuery.fromJson(readerToUse.reset());
                } else {
                    return fromJsonKnownDiscriminator(readerToUse.reset());
                }
            }
        });
    }

    static PrometheusEnrichmentItem fromJsonKnownDiscriminator(JsonReader jsonReader) throws IOException {
        return jsonReader.readObject(reader -> {
            PrometheusEnrichmentItem deserializedPrometheusEnrichmentItem = new PrometheusEnrichmentItem();
            while (reader.nextToken() != JsonToken.END_OBJECT) {
                String fieldName = reader.getFieldName();
                reader.nextToken();

                if ("title".equals(fieldName)) {
                    deserializedPrometheusEnrichmentItem.withTitle(reader.getString());
                } else if ("description".equals(fieldName)) {
                    deserializedPrometheusEnrichmentItem.withDescription(reader.getString());
                } else if ("status".equals(fieldName)) {
                    deserializedPrometheusEnrichmentItem.withStatus(Status.fromString(reader.getString()));
                } else if ("errorMessage".equals(fieldName)) {
                    deserializedPrometheusEnrichmentItem.withErrorMessage(reader.getString());
                } else if ("linkToApi".equals(fieldName)) {
                    deserializedPrometheusEnrichmentItem.linkToApi = reader.getString();
                } else if ("datasources".equals(fieldName)) {
                    List<String> datasources = reader.readArray(reader1 -> reader1.getString());
                    deserializedPrometheusEnrichmentItem.datasources = datasources;
                } else if ("grafanaExplorePath".equals(fieldName)) {
                    deserializedPrometheusEnrichmentItem.grafanaExplorePath = reader.getString();
                } else if ("query".equals(fieldName)) {
                    deserializedPrometheusEnrichmentItem.query = reader.getString();
                } else if ("type".equals(fieldName)) {
                    deserializedPrometheusEnrichmentItem.type = Type.fromString(reader.getString());
                } else {
                    reader.skipChildren();
                }
            }

            return deserializedPrometheusEnrichmentItem;
        });
    }
}
