// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.app.models;

import com.azure.core.annotation.Fluent;
import com.azure.core.util.CoreUtils;
import com.azure.core.util.logging.ClientLogger;
import com.azure.json.JsonReader;
import com.azure.json.JsonToken;
import com.azure.json.JsonWriter;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.time.format.DateTimeFormatter;
import java.util.List;

/**
 * Prometheus instant query enrichment object.
 */
@Fluent
public final class PrometheusRangeQuery extends AlertEnrichmentItem {
    /*
     * The enrichment type.
     */
    private Type type = Type.PROMETHEUS_RANGE_QUERY;

    /*
     * Link to Prometheus query API (Url format).
     */
    private String linkToApi;

    /*
     * An array of the azure monitor workspace resource ids.
     */
    private List<String> datasources;

    /*
     * Partial link to the Grafana explore API.
     */
    private String grafanaExplorePath;

    /*
     * The Prometheus expression query.
     */
    private String query;

    /*
     * The start evaluation date and time in ISO8601 format.
     */
    private OffsetDateTime start;

    /*
     * The end evaluation date and time in ISO8601 format.
     */
    private OffsetDateTime end;

    /*
     * Query resolution step width in ISO8601 format.
     */
    private String step;

    /**
     * Creates an instance of PrometheusRangeQuery class.
     */
    public PrometheusRangeQuery() {
    }

    /**
     * Get the type property: The enrichment type.
     * 
     * @return the type value.
     */
    @Override
    public Type type() {
        return this.type;
    }

    /**
     * Get the linkToApi property: Link to Prometheus query API (Url format).
     * 
     * @return the linkToApi value.
     */
    public String linkToApi() {
        return this.linkToApi;
    }

    /**
     * Set the linkToApi property: Link to Prometheus query API (Url format).
     * 
     * @param linkToApi the linkToApi value to set.
     * @return the PrometheusRangeQuery object itself.
     */
    public PrometheusRangeQuery withLinkToApi(String linkToApi) {
        this.linkToApi = linkToApi;
        return this;
    }

    /**
     * Get the datasources property: An array of the azure monitor workspace resource ids.
     * 
     * @return the datasources value.
     */
    public List<String> datasources() {
        return this.datasources;
    }

    /**
     * Set the datasources property: An array of the azure monitor workspace resource ids.
     * 
     * @param datasources the datasources value to set.
     * @return the PrometheusRangeQuery object itself.
     */
    public PrometheusRangeQuery withDatasources(List<String> datasources) {
        this.datasources = datasources;
        return this;
    }

    /**
     * Get the grafanaExplorePath property: Partial link to the Grafana explore API.
     * 
     * @return the grafanaExplorePath value.
     */
    public String grafanaExplorePath() {
        return this.grafanaExplorePath;
    }

    /**
     * Set the grafanaExplorePath property: Partial link to the Grafana explore API.
     * 
     * @param grafanaExplorePath the grafanaExplorePath value to set.
     * @return the PrometheusRangeQuery object itself.
     */
    public PrometheusRangeQuery withGrafanaExplorePath(String grafanaExplorePath) {
        this.grafanaExplorePath = grafanaExplorePath;
        return this;
    }

    /**
     * Get the query property: The Prometheus expression query.
     * 
     * @return the query value.
     */
    public String query() {
        return this.query;
    }

    /**
     * Set the query property: The Prometheus expression query.
     * 
     * @param query the query value to set.
     * @return the PrometheusRangeQuery object itself.
     */
    public PrometheusRangeQuery withQuery(String query) {
        this.query = query;
        return this;
    }

    /**
     * Get the start property: The start evaluation date and time in ISO8601 format.
     * 
     * @return the start value.
     */
    public OffsetDateTime start() {
        return this.start;
    }

    /**
     * Set the start property: The start evaluation date and time in ISO8601 format.
     * 
     * @param start the start value to set.
     * @return the PrometheusRangeQuery object itself.
     */
    public PrometheusRangeQuery withStart(OffsetDateTime start) {
        this.start = start;
        return this;
    }

    /**
     * Get the end property: The end evaluation date and time in ISO8601 format.
     * 
     * @return the end value.
     */
    public OffsetDateTime end() {
        return this.end;
    }

    /**
     * Set the end property: The end evaluation date and time in ISO8601 format.
     * 
     * @param end the end value to set.
     * @return the PrometheusRangeQuery object itself.
     */
    public PrometheusRangeQuery withEnd(OffsetDateTime end) {
        this.end = end;
        return this;
    }

    /**
     * Get the step property: Query resolution step width in ISO8601 format.
     * 
     * @return the step value.
     */
    public String step() {
        return this.step;
    }

    /**
     * Set the step property: Query resolution step width in ISO8601 format.
     * 
     * @param step the step value to set.
     * @return the PrometheusRangeQuery object itself.
     */
    public PrometheusRangeQuery withStep(String step) {
        this.step = step;
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PrometheusRangeQuery withTitle(String title) {
        super.withTitle(title);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PrometheusRangeQuery withDescription(String description) {
        super.withDescription(description);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PrometheusRangeQuery withStatus(Status status) {
        super.withStatus(status);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PrometheusRangeQuery withErrorMessage(String errorMessage) {
        super.withErrorMessage(errorMessage);
        return this;
    }

    /**
     * Validates the instance.
     * 
     * @throws IllegalArgumentException thrown if the instance is not valid.
     */
    @Override
    public void validate() {
        if (linkToApi() == null) {
            throw LOGGER.atError()
                .log(new IllegalArgumentException("Missing required property linkToApi in model PrometheusRangeQuery"));
        }
        if (datasources() == null) {
            throw LOGGER.atError()
                .log(new IllegalArgumentException(
                    "Missing required property datasources in model PrometheusRangeQuery"));
        }
        if (grafanaExplorePath() == null) {
            throw LOGGER.atError()
                .log(new IllegalArgumentException(
                    "Missing required property grafanaExplorePath in model PrometheusRangeQuery"));
        }
        if (query() == null) {
            throw LOGGER.atError()
                .log(new IllegalArgumentException("Missing required property query in model PrometheusRangeQuery"));
        }
        if (start() == null) {
            throw LOGGER.atError()
                .log(new IllegalArgumentException("Missing required property start in model PrometheusRangeQuery"));
        }
        if (end() == null) {
            throw LOGGER.atError()
                .log(new IllegalArgumentException("Missing required property end in model PrometheusRangeQuery"));
        }
        if (step() == null) {
            throw LOGGER.atError()
                .log(new IllegalArgumentException("Missing required property step in model PrometheusRangeQuery"));
        }
        if (title() == null) {
            throw LOGGER.atError()
                .log(new IllegalArgumentException("Missing required property title in model PrometheusRangeQuery"));
        }
        if (description() == null) {
            throw LOGGER.atError()
                .log(new IllegalArgumentException(
                    "Missing required property description in model PrometheusRangeQuery"));
        }
        if (status() == null) {
            throw LOGGER.atError()
                .log(new IllegalArgumentException("Missing required property status in model PrometheusRangeQuery"));
        }
    }

    private static final ClientLogger LOGGER = new ClientLogger(PrometheusRangeQuery.class);

    /**
     * {@inheritDoc}
     */
    @Override
    public JsonWriter toJson(JsonWriter jsonWriter) throws IOException {
        jsonWriter.writeStartObject();
        jsonWriter.writeStringField("title", title());
        jsonWriter.writeStringField("description", description());
        jsonWriter.writeStringField("status", status() == null ? null : status().toString());
        jsonWriter.writeStringField("errorMessage", errorMessage());
        jsonWriter.writeStringField("linkToApi", this.linkToApi);
        jsonWriter.writeArrayField("datasources", this.datasources, (writer, element) -> writer.writeString(element));
        jsonWriter.writeStringField("grafanaExplorePath", this.grafanaExplorePath);
        jsonWriter.writeStringField("query", this.query);
        jsonWriter.writeStringField("start",
            this.start == null ? null : DateTimeFormatter.ISO_OFFSET_DATE_TIME.format(this.start));
        jsonWriter.writeStringField("end",
            this.end == null ? null : DateTimeFormatter.ISO_OFFSET_DATE_TIME.format(this.end));
        jsonWriter.writeStringField("step", this.step);
        jsonWriter.writeStringField("type", this.type == null ? null : this.type.toString());
        return jsonWriter.writeEndObject();
    }

    /**
     * Reads an instance of PrometheusRangeQuery from the JsonReader.
     * 
     * @param jsonReader The JsonReader being read.
     * @return An instance of PrometheusRangeQuery if the JsonReader was pointing to an instance of it, or null if it
     * was pointing to JSON null.
     * @throws IllegalStateException If the deserialized JSON object was missing any required properties.
     * @throws IOException If an error occurs while reading the PrometheusRangeQuery.
     */
    public static PrometheusRangeQuery fromJson(JsonReader jsonReader) throws IOException {
        return jsonReader.readObject(reader -> {
            PrometheusRangeQuery deserializedPrometheusRangeQuery = new PrometheusRangeQuery();
            while (reader.nextToken() != JsonToken.END_OBJECT) {
                String fieldName = reader.getFieldName();
                reader.nextToken();

                if ("title".equals(fieldName)) {
                    deserializedPrometheusRangeQuery.withTitle(reader.getString());
                } else if ("description".equals(fieldName)) {
                    deserializedPrometheusRangeQuery.withDescription(reader.getString());
                } else if ("status".equals(fieldName)) {
                    deserializedPrometheusRangeQuery.withStatus(Status.fromString(reader.getString()));
                } else if ("errorMessage".equals(fieldName)) {
                    deserializedPrometheusRangeQuery.withErrorMessage(reader.getString());
                } else if ("linkToApi".equals(fieldName)) {
                    deserializedPrometheusRangeQuery.linkToApi = reader.getString();
                } else if ("datasources".equals(fieldName)) {
                    List<String> datasources = reader.readArray(reader1 -> reader1.getString());
                    deserializedPrometheusRangeQuery.datasources = datasources;
                } else if ("grafanaExplorePath".equals(fieldName)) {
                    deserializedPrometheusRangeQuery.grafanaExplorePath = reader.getString();
                } else if ("query".equals(fieldName)) {
                    deserializedPrometheusRangeQuery.query = reader.getString();
                } else if ("start".equals(fieldName)) {
                    deserializedPrometheusRangeQuery.start = reader
                        .getNullable(nonNullReader -> CoreUtils.parseBestOffsetDateTime(nonNullReader.getString()));
                } else if ("end".equals(fieldName)) {
                    deserializedPrometheusRangeQuery.end = reader
                        .getNullable(nonNullReader -> CoreUtils.parseBestOffsetDateTime(nonNullReader.getString()));
                } else if ("step".equals(fieldName)) {
                    deserializedPrometheusRangeQuery.step = reader.getString();
                } else if ("type".equals(fieldName)) {
                    deserializedPrometheusRangeQuery.type = Type.fromString(reader.getString());
                } else {
                    reader.skipChildren();
                }
            }

            return deserializedPrometheusRangeQuery;
        });
    }
}
