// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.app.models;

import com.azure.core.annotation.Fluent;
import com.azure.core.util.logging.ClientLogger;
import com.azure.json.JsonReader;
import com.azure.json.JsonToken;
import com.azure.json.JsonWriter;
import java.io.IOException;
import java.util.List;

/**
 * Prometheus instant query enrichment object.
 */
@Fluent
public final class PrometheusInstantQuery extends PrometheusEnrichmentItem {
    /*
     * The enrichment type.
     */
    private Type type = Type.PROMETHEUS_INSTANT_QUERY;

    /*
     * The date and the time of the evaluation.
     */
    private String time;

    /**
     * Creates an instance of PrometheusInstantQuery class.
     */
    public PrometheusInstantQuery() {
    }

    /**
     * Get the type property: The enrichment type.
     * 
     * @return the type value.
     */
    @Override
    public Type type() {
        return this.type;
    }

    /**
     * Get the time property: The date and the time of the evaluation.
     * 
     * @return the time value.
     */
    public String time() {
        return this.time;
    }

    /**
     * Set the time property: The date and the time of the evaluation.
     * 
     * @param time the time value to set.
     * @return the PrometheusInstantQuery object itself.
     */
    public PrometheusInstantQuery withTime(String time) {
        this.time = time;
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PrometheusInstantQuery withLinkToApi(String linkToApi) {
        super.withLinkToApi(linkToApi);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PrometheusInstantQuery withDatasources(List<String> datasources) {
        super.withDatasources(datasources);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PrometheusInstantQuery withGrafanaExplorePath(String grafanaExplorePath) {
        super.withGrafanaExplorePath(grafanaExplorePath);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PrometheusInstantQuery withQuery(String query) {
        super.withQuery(query);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PrometheusInstantQuery withTitle(String title) {
        super.withTitle(title);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PrometheusInstantQuery withDescription(String description) {
        super.withDescription(description);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PrometheusInstantQuery withStatus(Status status) {
        super.withStatus(status);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PrometheusInstantQuery withErrorMessage(String errorMessage) {
        super.withErrorMessage(errorMessage);
        return this;
    }

    /**
     * Validates the instance.
     * 
     * @throws IllegalArgumentException thrown if the instance is not valid.
     */
    @Override
    public void validate() {
        if (time() == null) {
            throw LOGGER.atError()
                .log(new IllegalArgumentException("Missing required property time in model PrometheusInstantQuery"));
        }
        if (title() == null) {
            throw LOGGER.atError()
                .log(new IllegalArgumentException("Missing required property title in model PrometheusInstantQuery"));
        }
        if (description() == null) {
            throw LOGGER.atError()
                .log(new IllegalArgumentException(
                    "Missing required property description in model PrometheusInstantQuery"));
        }
        if (status() == null) {
            throw LOGGER.atError()
                .log(new IllegalArgumentException("Missing required property status in model PrometheusInstantQuery"));
        }
        if (linkToApi() == null) {
            throw LOGGER.atError()
                .log(new IllegalArgumentException(
                    "Missing required property linkToApi in model PrometheusInstantQuery"));
        }
        if (datasources() == null) {
            throw LOGGER.atError()
                .log(new IllegalArgumentException(
                    "Missing required property datasources in model PrometheusInstantQuery"));
        }
        if (grafanaExplorePath() == null) {
            throw LOGGER.atError()
                .log(new IllegalArgumentException(
                    "Missing required property grafanaExplorePath in model PrometheusInstantQuery"));
        }
        if (query() == null) {
            throw LOGGER.atError()
                .log(new IllegalArgumentException("Missing required property query in model PrometheusInstantQuery"));
        }
    }

    private static final ClientLogger LOGGER = new ClientLogger(PrometheusInstantQuery.class);

    /**
     * {@inheritDoc}
     */
    @Override
    public JsonWriter toJson(JsonWriter jsonWriter) throws IOException {
        jsonWriter.writeStartObject();
        jsonWriter.writeStringField("title", title());
        jsonWriter.writeStringField("description", description());
        jsonWriter.writeStringField("status", status() == null ? null : status().toString());
        jsonWriter.writeStringField("linkToApi", linkToApi());
        jsonWriter.writeArrayField("datasources", datasources(), (writer, element) -> writer.writeString(element));
        jsonWriter.writeStringField("grafanaExplorePath", grafanaExplorePath());
        jsonWriter.writeStringField("query", query());
        jsonWriter.writeStringField("errorMessage", errorMessage());
        jsonWriter.writeStringField("time", this.time);
        jsonWriter.writeStringField("type", this.type == null ? null : this.type.toString());
        return jsonWriter.writeEndObject();
    }

    /**
     * Reads an instance of PrometheusInstantQuery from the JsonReader.
     * 
     * @param jsonReader The JsonReader being read.
     * @return An instance of PrometheusInstantQuery if the JsonReader was pointing to an instance of it, or null if it
     * was pointing to JSON null.
     * @throws IllegalStateException If the deserialized JSON object was missing any required properties.
     * @throws IOException If an error occurs while reading the PrometheusInstantQuery.
     */
    public static PrometheusInstantQuery fromJson(JsonReader jsonReader) throws IOException {
        return jsonReader.readObject(reader -> {
            PrometheusInstantQuery deserializedPrometheusInstantQuery = new PrometheusInstantQuery();
            while (reader.nextToken() != JsonToken.END_OBJECT) {
                String fieldName = reader.getFieldName();
                reader.nextToken();

                if ("title".equals(fieldName)) {
                    deserializedPrometheusInstantQuery.withTitle(reader.getString());
                } else if ("description".equals(fieldName)) {
                    deserializedPrometheusInstantQuery.withDescription(reader.getString());
                } else if ("status".equals(fieldName)) {
                    deserializedPrometheusInstantQuery.withStatus(Status.fromString(reader.getString()));
                } else if ("linkToApi".equals(fieldName)) {
                    deserializedPrometheusInstantQuery.withLinkToApi(reader.getString());
                } else if ("datasources".equals(fieldName)) {
                    List<String> datasources = reader.readArray(reader1 -> reader1.getString());
                    deserializedPrometheusInstantQuery.withDatasources(datasources);
                } else if ("grafanaExplorePath".equals(fieldName)) {
                    deserializedPrometheusInstantQuery.withGrafanaExplorePath(reader.getString());
                } else if ("query".equals(fieldName)) {
                    deserializedPrometheusInstantQuery.withQuery(reader.getString());
                } else if ("errorMessage".equals(fieldName)) {
                    deserializedPrometheusInstantQuery.withErrorMessage(reader.getString());
                } else if ("time".equals(fieldName)) {
                    deserializedPrometheusInstantQuery.time = reader.getString();
                } else if ("type".equals(fieldName)) {
                    deserializedPrometheusInstantQuery.type = Type.fromString(reader.getString());
                } else {
                    reader.skipChildren();
                }
            }

            return deserializedPrometheusInstantQuery;
        });
    }
}
