// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.app.models;

import com.azure.core.annotation.Fluent;
import com.azure.json.JsonReader;
import com.azure.json.JsonToken;
import com.azure.json.JsonWriter;
import java.io.IOException;

/**
 * The PropertyChangeDetails model.
 */
@Fluent
public final class PropertyChangeDetails extends BaseDetails {
    /*
     * Type of modification details
     */
    private AlertModificationType type = AlertModificationType.PROPERTY_CHANGE;

    /*
     * The value before the change
     */
    private String oldValue;

    /*
     * The value after the change
     */
    private String newValue;

    /*
     * The comment
     */
    private String comment;

    /**
     * Creates an instance of PropertyChangeDetails class.
     */
    public PropertyChangeDetails() {
    }

    /**
     * Get the type property: Type of modification details.
     * 
     * @return the type value.
     */
    @Override
    public AlertModificationType type() {
        return this.type;
    }

    /**
     * Get the oldValue property: The value before the change.
     * 
     * @return the oldValue value.
     */
    public String oldValue() {
        return this.oldValue;
    }

    /**
     * Set the oldValue property: The value before the change.
     * 
     * @param oldValue the oldValue value to set.
     * @return the PropertyChangeDetails object itself.
     */
    public PropertyChangeDetails withOldValue(String oldValue) {
        this.oldValue = oldValue;
        return this;
    }

    /**
     * Get the newValue property: The value after the change.
     * 
     * @return the newValue value.
     */
    public String newValue() {
        return this.newValue;
    }

    /**
     * Set the newValue property: The value after the change.
     * 
     * @param newValue the newValue value to set.
     * @return the PropertyChangeDetails object itself.
     */
    public PropertyChangeDetails withNewValue(String newValue) {
        this.newValue = newValue;
        return this;
    }

    /**
     * Get the comment property: The comment.
     * 
     * @return the comment value.
     */
    public String comment() {
        return this.comment;
    }

    /**
     * Set the comment property: The comment.
     * 
     * @param comment the comment value to set.
     * @return the PropertyChangeDetails object itself.
     */
    public PropertyChangeDetails withComment(String comment) {
        this.comment = comment;
        return this;
    }

    /**
     * Validates the instance.
     * 
     * @throws IllegalArgumentException thrown if the instance is not valid.
     */
    @Override
    public void validate() {
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public JsonWriter toJson(JsonWriter jsonWriter) throws IOException {
        jsonWriter.writeStartObject();
        jsonWriter.writeStringField("type", this.type == null ? null : this.type.toString());
        jsonWriter.writeStringField("oldValue", this.oldValue);
        jsonWriter.writeStringField("newValue", this.newValue);
        jsonWriter.writeStringField("comment", this.comment);
        return jsonWriter.writeEndObject();
    }

    /**
     * Reads an instance of PropertyChangeDetails from the JsonReader.
     * 
     * @param jsonReader The JsonReader being read.
     * @return An instance of PropertyChangeDetails if the JsonReader was pointing to an instance of it, or null if it
     * was pointing to JSON null.
     * @throws IOException If an error occurs while reading the PropertyChangeDetails.
     */
    public static PropertyChangeDetails fromJson(JsonReader jsonReader) throws IOException {
        return jsonReader.readObject(reader -> {
            PropertyChangeDetails deserializedPropertyChangeDetails = new PropertyChangeDetails();
            while (reader.nextToken() != JsonToken.END_OBJECT) {
                String fieldName = reader.getFieldName();
                reader.nextToken();

                if ("type".equals(fieldName)) {
                    deserializedPropertyChangeDetails.type = AlertModificationType.fromString(reader.getString());
                } else if ("oldValue".equals(fieldName)) {
                    deserializedPropertyChangeDetails.oldValue = reader.getString();
                } else if ("newValue".equals(fieldName)) {
                    deserializedPropertyChangeDetails.newValue = reader.getString();
                } else if ("comment".equals(fieldName)) {
                    deserializedPropertyChangeDetails.comment = reader.getString();
                } else {
                    reader.skipChildren();
                }
            }

            return deserializedPropertyChangeDetails;
        });
    }
}
