// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.app.models;

import com.azure.core.util.ExpandableStringEnum;
import java.util.Collection;

/**
 * The status of the notification.
 */
public final class ResultStatus extends ExpandableStringEnum<ResultStatus> {
    /**
     * Static value None for ResultStatus.
     */
    public static final ResultStatus NONE = fromString("None");

    /**
     * Static value Inline for ResultStatus.
     */
    public static final ResultStatus INLINE = fromString("Inline");

    /**
     * Static value Throttled for ResultStatus.
     */
    public static final ResultStatus THROTTLED = fromString("Throttled");

    /**
     * Static value Failed for ResultStatus.
     */
    public static final ResultStatus FAILED = fromString("Failed");

    /**
     * Static value ThrottledByAlertRule for ResultStatus.
     */
    public static final ResultStatus THROTTLED_BY_ALERT_RULE = fromString("ThrottledByAlertRule");

    /**
     * Static value ThrottledBySubscription for ResultStatus.
     */
    public static final ResultStatus THROTTLED_BY_SUBSCRIPTION = fromString("ThrottledBySubscription");

    /**
     * Creates a new instance of ResultStatus value.
     * 
     * @deprecated Use the {@link #fromString(String)} factory method.
     */
    @Deprecated
    public ResultStatus() {
    }

    /**
     * Creates or finds a ResultStatus from its string representation.
     * 
     * @param name a name to look for.
     * @return the corresponding ResultStatus.
     */
    public static ResultStatus fromString(String name) {
        return fromString(name, ResultStatus.class);
    }

    /**
     * Gets known ResultStatus values.
     * 
     * @return known ResultStatus values.
     */
    public static Collection<ResultStatus> values() {
        return values(ResultStatus.class);
    }
}
