// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.app.models;

import com.azure.core.annotation.Fluent;
import com.azure.json.JsonReader;
import com.azure.json.JsonSerializable;
import com.azure.json.JsonToken;
import com.azure.json.JsonWriter;
import java.io.IOException;

/**
 * The TriggeredRule model.
 */
@Fluent
public final class TriggeredRule implements JsonSerializable<TriggeredRule> {
    /*
     * The action group ID
     */
    private String actionGroupId;

    /*
     * The rule ID
     */
    private String ruleId;

    /*
     * The rule type
     */
    private RuleType ruleType;

    /**
     * Creates an instance of TriggeredRule class.
     */
    public TriggeredRule() {
    }

    /**
     * Get the actionGroupId property: The action group ID.
     * 
     * @return the actionGroupId value.
     */
    public String actionGroupId() {
        return this.actionGroupId;
    }

    /**
     * Set the actionGroupId property: The action group ID.
     * 
     * @param actionGroupId the actionGroupId value to set.
     * @return the TriggeredRule object itself.
     */
    public TriggeredRule withActionGroupId(String actionGroupId) {
        this.actionGroupId = actionGroupId;
        return this;
    }

    /**
     * Get the ruleId property: The rule ID.
     * 
     * @return the ruleId value.
     */
    public String ruleId() {
        return this.ruleId;
    }

    /**
     * Set the ruleId property: The rule ID.
     * 
     * @param ruleId the ruleId value to set.
     * @return the TriggeredRule object itself.
     */
    public TriggeredRule withRuleId(String ruleId) {
        this.ruleId = ruleId;
        return this;
    }

    /**
     * Get the ruleType property: The rule type.
     * 
     * @return the ruleType value.
     */
    public RuleType ruleType() {
        return this.ruleType;
    }

    /**
     * Set the ruleType property: The rule type.
     * 
     * @param ruleType the ruleType value to set.
     * @return the TriggeredRule object itself.
     */
    public TriggeredRule withRuleType(RuleType ruleType) {
        this.ruleType = ruleType;
        return this;
    }

    /**
     * Validates the instance.
     * 
     * @throws IllegalArgumentException thrown if the instance is not valid.
     */
    public void validate() {
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public JsonWriter toJson(JsonWriter jsonWriter) throws IOException {
        jsonWriter.writeStartObject();
        jsonWriter.writeStringField("actionGroupId", this.actionGroupId);
        jsonWriter.writeStringField("ruleId", this.ruleId);
        jsonWriter.writeStringField("ruleType", this.ruleType == null ? null : this.ruleType.toString());
        return jsonWriter.writeEndObject();
    }

    /**
     * Reads an instance of TriggeredRule from the JsonReader.
     * 
     * @param jsonReader The JsonReader being read.
     * @return An instance of TriggeredRule if the JsonReader was pointing to an instance of it, or null if it was
     * pointing to JSON null.
     * @throws IOException If an error occurs while reading the TriggeredRule.
     */
    public static TriggeredRule fromJson(JsonReader jsonReader) throws IOException {
        return jsonReader.readObject(reader -> {
            TriggeredRule deserializedTriggeredRule = new TriggeredRule();
            while (reader.nextToken() != JsonToken.END_OBJECT) {
                String fieldName = reader.getFieldName();
                reader.nextToken();

                if ("actionGroupId".equals(fieldName)) {
                    deserializedTriggeredRule.actionGroupId = reader.getString();
                } else if ("ruleId".equals(fieldName)) {
                    deserializedTriggeredRule.ruleId = reader.getString();
                } else if ("ruleType".equals(fieldName)) {
                    deserializedTriggeredRule.ruleType = RuleType.fromString(reader.getString());
                } else {
                    reader.skipChildren();
                }
            }

            return deserializedTriggeredRule;
        });
    }
}
