// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

/**
 * Package containing the data models for TenantLevelActivityLogAlertRulesInAlertsManagementResourceProvider.
 * Tenant Level Activity Log Alert Rules provides rules creation on management group level.
 */
package com.azure.app.models;
