// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.app.fluent;

import com.azure.app.fluent.models.PreviewAlertRuleResponseInner;
import com.azure.app.models.PreviewAlertRuleRequest;
import com.azure.core.annotation.ReturnType;
import com.azure.core.annotation.ServiceMethod;
import com.azure.core.http.rest.Response;
import com.azure.core.util.Context;

/**
 * An instance of this class provides access to all the operations defined in ResourceProvidersClient.
 */
public interface ResourceProvidersClient {
    /**
     * Retrieves the results of a simulated historical execution of an alert rule.
     * 
     * @param resourceId The resourceId parameter.
     * @param parameters The parameters parameter.
     * @param context The context to associate with this operation.
     * @throws IllegalArgumentException thrown if parameters fail the validation.
     * @throws com.azure.core.management.exception.ManagementException thrown if the request is rejected by server.
     * @throws RuntimeException all other wrapped checked exceptions if the request fails to be sent.
     * @return the response body along with {@link Response}.
     */
    @ServiceMethod(returns = ReturnType.SINGLE)
    Response<PreviewAlertRuleResponseInner> previewAlertRuleWithResponse(String resourceId,
        PreviewAlertRuleRequest parameters, Context context);

    /**
     * Retrieves the results of a simulated historical execution of an alert rule.
     * 
     * @param resourceId The resourceId parameter.
     * @param parameters The parameters parameter.
     * @throws IllegalArgumentException thrown if parameters fail the validation.
     * @throws com.azure.core.management.exception.ManagementException thrown if the request is rejected by server.
     * @throws RuntimeException all other wrapped checked exceptions if the request fails to be sent.
     * @return the response.
     */
    @ServiceMethod(returns = ReturnType.SINGLE)
    PreviewAlertRuleResponseInner previewAlertRule(String resourceId, PreviewAlertRuleRequest parameters);
}
