// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.app.implementation;

import com.azure.app.fluent.models.AlertModificationInner;
import com.azure.app.models.AlertModification;
import com.azure.app.models.AlertModificationProperties;

public final class AlertModificationImpl implements AlertModification {
    private AlertModificationInner innerObject;

    private final com.azure.app.AppManager serviceManager;

    AlertModificationImpl(AlertModificationInner innerObject, com.azure.app.AppManager serviceManager) {
        this.innerObject = innerObject;
        this.serviceManager = serviceManager;
    }

    public String id() {
        return this.innerModel().id();
    }

    public String name() {
        return this.innerModel().name();
    }

    public String type() {
        return this.innerModel().type();
    }

    public AlertModificationProperties properties() {
        return this.innerModel().properties();
    }

    public AlertModificationInner innerModel() {
        return this.innerObject;
    }

    private com.azure.app.AppManager manager() {
        return this.serviceManager;
    }
}
