// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.app.implementation;

import com.azure.app.fluent.models.AlertsSummaryInner;
import com.azure.app.models.AlertsSummary;
import com.azure.app.models.AlertsSummaryGroup;

public final class AlertsSummaryImpl implements AlertsSummary {
    private AlertsSummaryInner innerObject;

    private final com.azure.app.AppManager serviceManager;

    AlertsSummaryImpl(AlertsSummaryInner innerObject, com.azure.app.AppManager serviceManager) {
        this.innerObject = innerObject;
        this.serviceManager = serviceManager;
    }

    public String id() {
        return this.innerModel().id();
    }

    public String name() {
        return this.innerModel().name();
    }

    public String type() {
        return this.innerModel().type();
    }

    public AlertsSummaryGroup properties() {
        return this.innerModel().properties();
    }

    public AlertsSummaryInner innerModel() {
        return this.innerObject;
    }

    private com.azure.app.AppManager manager() {
        return this.serviceManager;
    }
}
