// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.app.implementation;

import com.azure.app.fluent.models.AlertEnrichmentResponseInner;
import com.azure.app.models.AlertEnrichmentProperties;
import com.azure.app.models.AlertEnrichmentResponse;
import com.azure.core.management.SystemData;

public final class AlertEnrichmentResponseImpl implements AlertEnrichmentResponse {
    private AlertEnrichmentResponseInner innerObject;

    private final com.azure.app.AppManager serviceManager;

    AlertEnrichmentResponseImpl(AlertEnrichmentResponseInner innerObject, com.azure.app.AppManager serviceManager) {
        this.innerObject = innerObject;
        this.serviceManager = serviceManager;
    }

    public String id() {
        return this.innerModel().id();
    }

    public String name() {
        return this.innerModel().name();
    }

    public String type() {
        return this.innerModel().type();
    }

    public AlertEnrichmentProperties properties() {
        return this.innerModel().properties();
    }

    public SystemData systemData() {
        return this.innerModel().systemData();
    }

    public AlertEnrichmentResponseInner innerModel() {
        return this.innerObject;
    }

    private com.azure.app.AppManager manager() {
        return this.serviceManager;
    }
}
