// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.app.implementation;

import com.azure.app.fluent.models.AlertInner;
import com.azure.app.models.Alert;
import com.azure.app.models.AlertProperties;
import com.azure.core.management.SystemData;

public final class AlertImpl implements Alert {
    private AlertInner innerObject;

    private final com.azure.app.AppManager serviceManager;

    AlertImpl(AlertInner innerObject, com.azure.app.AppManager serviceManager) {
        this.innerObject = innerObject;
        this.serviceManager = serviceManager;
    }

    public String id() {
        return this.innerModel().id();
    }

    public String name() {
        return this.innerModel().name();
    }

    public String type() {
        return this.innerModel().type();
    }

    public AlertProperties properties() {
        return this.innerModel().properties();
    }

    public SystemData systemData() {
        return this.innerModel().systemData();
    }

    public AlertInner innerModel() {
        return this.innerObject;
    }

    private com.azure.app.AppManager manager() {
        return this.serviceManager;
    }
}
