// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.app.implementation;

import com.azure.app.fluent.models.AlertsMetadataInner;
import com.azure.app.models.AlertsMetadata;
import com.azure.app.models.AlertsMetadataProperties;

public final class AlertsMetadataImpl implements AlertsMetadata {
    private AlertsMetadataInner innerObject;

    private final com.azure.app.AppManager serviceManager;

    AlertsMetadataImpl(AlertsMetadataInner innerObject, com.azure.app.AppManager serviceManager) {
        this.innerObject = innerObject;
        this.serviceManager = serviceManager;
    }

    public AlertsMetadataProperties properties() {
        return this.innerModel().properties();
    }

    public AlertsMetadataInner innerModel() {
        return this.innerObject;
    }

    private com.azure.app.AppManager manager() {
        return this.serviceManager;
    }
}
