// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.app.models;

import com.azure.core.util.ExpandableStringEnum;
import java.util.Collection;

/**
 * The state of the alert after the evaluation.
 */
public final class AlertState extends ExpandableStringEnum<AlertState> {
    /**
     * Static value NoAlert for AlertState.
     */
    public static final AlertState NO_ALERT = fromString("NoAlert");

    /**
     * Static value Fired for AlertState.
     */
    public static final AlertState FIRED = fromString("Fired");

    /**
     * Static value Firing for AlertState.
     */
    public static final AlertState FIRING = fromString("Firing");

    /**
     * Static value Resolving for AlertState.
     */
    public static final AlertState RESOLVING = fromString("Resolving");

    /**
     * Static value Resolved for AlertState.
     */
    public static final AlertState RESOLVED = fromString("Resolved");

    /**
     * Creates a new instance of AlertState value.
     * 
     * @deprecated Use the {@link #fromString(String)} factory method.
     */
    @Deprecated
    public AlertState() {
    }

    /**
     * Creates or finds a AlertState from its string representation.
     * 
     * @param name a name to look for.
     * @return the corresponding AlertState.
     */
    public static AlertState fromString(String name) {
        return fromString(name, AlertState.class);
    }

    /**
     * Gets known AlertState values.
     * 
     * @return known AlertState values.
     */
    public static Collection<AlertState> values() {
        return values(AlertState.class);
    }
}
