// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.app.models;

import com.azure.core.annotation.Fluent;
import com.azure.core.util.CoreUtils;
import com.azure.json.JsonReader;
import com.azure.json.JsonSerializable;
import com.azure.json.JsonToken;
import com.azure.json.JsonWriter;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.time.format.DateTimeFormatter;

/**
 * Details of the evaluated period.
 */
@Fluent
public final class EvaluatedPeriod implements JsonSerializable<EvaluatedPeriod> {
    /*
     * The timestamp of the evaluated period.
     */
    private OffsetDateTime timestamp;

    /*
     * The high threshold value for the evaluation period.
     */
    private Double highThreshold;

    /*
     * The low threshold value for the evaluation period.
     */
    private Double lowThreshold;

    /*
     * The metric value for the evaluation period.
     */
    private Double metricValue;

    /*
     * Indicates whether the threshold was met during the evaluation period.
     */
    private Boolean thresholdMet;

    /**
     * Creates an instance of EvaluatedPeriod class.
     */
    public EvaluatedPeriod() {
    }

    /**
     * Get the timestamp property: The timestamp of the evaluated period.
     * 
     * @return the timestamp value.
     */
    public OffsetDateTime timestamp() {
        return this.timestamp;
    }

    /**
     * Set the timestamp property: The timestamp of the evaluated period.
     * 
     * @param timestamp the timestamp value to set.
     * @return the EvaluatedPeriod object itself.
     */
    public EvaluatedPeriod withTimestamp(OffsetDateTime timestamp) {
        this.timestamp = timestamp;
        return this;
    }

    /**
     * Get the highThreshold property: The high threshold value for the evaluation period.
     * 
     * @return the highThreshold value.
     */
    public Double highThreshold() {
        return this.highThreshold;
    }

    /**
     * Set the highThreshold property: The high threshold value for the evaluation period.
     * 
     * @param highThreshold the highThreshold value to set.
     * @return the EvaluatedPeriod object itself.
     */
    public EvaluatedPeriod withHighThreshold(Double highThreshold) {
        this.highThreshold = highThreshold;
        return this;
    }

    /**
     * Get the lowThreshold property: The low threshold value for the evaluation period.
     * 
     * @return the lowThreshold value.
     */
    public Double lowThreshold() {
        return this.lowThreshold;
    }

    /**
     * Set the lowThreshold property: The low threshold value for the evaluation period.
     * 
     * @param lowThreshold the lowThreshold value to set.
     * @return the EvaluatedPeriod object itself.
     */
    public EvaluatedPeriod withLowThreshold(Double lowThreshold) {
        this.lowThreshold = lowThreshold;
        return this;
    }

    /**
     * Get the metricValue property: The metric value for the evaluation period.
     * 
     * @return the metricValue value.
     */
    public Double metricValue() {
        return this.metricValue;
    }

    /**
     * Set the metricValue property: The metric value for the evaluation period.
     * 
     * @param metricValue the metricValue value to set.
     * @return the EvaluatedPeriod object itself.
     */
    public EvaluatedPeriod withMetricValue(Double metricValue) {
        this.metricValue = metricValue;
        return this;
    }

    /**
     * Get the thresholdMet property: Indicates whether the threshold was met during the evaluation period.
     * 
     * @return the thresholdMet value.
     */
    public Boolean thresholdMet() {
        return this.thresholdMet;
    }

    /**
     * Set the thresholdMet property: Indicates whether the threshold was met during the evaluation period.
     * 
     * @param thresholdMet the thresholdMet value to set.
     * @return the EvaluatedPeriod object itself.
     */
    public EvaluatedPeriod withThresholdMet(Boolean thresholdMet) {
        this.thresholdMet = thresholdMet;
        return this;
    }

    /**
     * Validates the instance.
     * 
     * @throws IllegalArgumentException thrown if the instance is not valid.
     */
    public void validate() {
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public JsonWriter toJson(JsonWriter jsonWriter) throws IOException {
        jsonWriter.writeStartObject();
        jsonWriter.writeStringField("timestamp",
            this.timestamp == null ? null : DateTimeFormatter.ISO_OFFSET_DATE_TIME.format(this.timestamp));
        jsonWriter.writeNumberField("highThreshold", this.highThreshold);
        jsonWriter.writeNumberField("lowThreshold", this.lowThreshold);
        jsonWriter.writeNumberField("metricValue", this.metricValue);
        jsonWriter.writeBooleanField("thresholdMet", this.thresholdMet);
        return jsonWriter.writeEndObject();
    }

    /**
     * Reads an instance of EvaluatedPeriod from the JsonReader.
     * 
     * @param jsonReader The JsonReader being read.
     * @return An instance of EvaluatedPeriod if the JsonReader was pointing to an instance of it, or null if it was
     * pointing to JSON null.
     * @throws IOException If an error occurs while reading the EvaluatedPeriod.
     */
    public static EvaluatedPeriod fromJson(JsonReader jsonReader) throws IOException {
        return jsonReader.readObject(reader -> {
            EvaluatedPeriod deserializedEvaluatedPeriod = new EvaluatedPeriod();
            while (reader.nextToken() != JsonToken.END_OBJECT) {
                String fieldName = reader.getFieldName();
                reader.nextToken();

                if ("timestamp".equals(fieldName)) {
                    deserializedEvaluatedPeriod.timestamp = reader
                        .getNullable(nonNullReader -> CoreUtils.parseBestOffsetDateTime(nonNullReader.getString()));
                } else if ("highThreshold".equals(fieldName)) {
                    deserializedEvaluatedPeriod.highThreshold = reader.getNullable(JsonReader::getDouble);
                } else if ("lowThreshold".equals(fieldName)) {
                    deserializedEvaluatedPeriod.lowThreshold = reader.getNullable(JsonReader::getDouble);
                } else if ("metricValue".equals(fieldName)) {
                    deserializedEvaluatedPeriod.metricValue = reader.getNullable(JsonReader::getDouble);
                } else if ("thresholdMet".equals(fieldName)) {
                    deserializedEvaluatedPeriod.thresholdMet = reader.getNullable(JsonReader::getBoolean);
                } else {
                    reader.skipChildren();
                }
            }

            return deserializedEvaluatedPeriod;
        });
    }
}
