// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.app.models;

import com.azure.app.fluent.models.LogAlertRuleProperties;
import com.azure.core.annotation.Fluent;
import com.azure.core.util.logging.ClientLogger;
import com.azure.json.JsonReader;
import com.azure.json.JsonSerializable;
import com.azure.json.JsonToken;
import com.azure.json.JsonWriter;
import java.io.IOException;
import java.time.Duration;
import java.util.List;
import java.util.Map;

/**
 * The scheduled query rule resource.
 */
@Fluent
public final class LogAlertRuleResource implements JsonSerializable<LogAlertRuleResource> {
    /*
     * Resource tags.
     */
    private Map<String, String> tags;

    /*
     * The geo-location where the resource lives
     */
    private String location;

    /*
     * Indicates the type of scheduled query rule. The default is LogAlert.
     */
    private Kind kind;

    /*
     * The rule properties of the resource.
     */
    private LogAlertRuleProperties innerProperties = new LogAlertRuleProperties();

    /**
     * Creates an instance of LogAlertRuleResource class.
     */
    public LogAlertRuleResource() {
    }

    /**
     * Get the tags property: Resource tags.
     * 
     * @return the tags value.
     */
    public Map<String, String> tags() {
        return this.tags;
    }

    /**
     * Set the tags property: Resource tags.
     * 
     * @param tags the tags value to set.
     * @return the LogAlertRuleResource object itself.
     */
    public LogAlertRuleResource withTags(Map<String, String> tags) {
        this.tags = tags;
        return this;
    }

    /**
     * Get the location property: The geo-location where the resource lives.
     * 
     * @return the location value.
     */
    public String location() {
        return this.location;
    }

    /**
     * Set the location property: The geo-location where the resource lives.
     * 
     * @param location the location value to set.
     * @return the LogAlertRuleResource object itself.
     */
    public LogAlertRuleResource withLocation(String location) {
        this.location = location;
        return this;
    }

    /**
     * Get the kind property: Indicates the type of scheduled query rule. The default is LogAlert.
     * 
     * @return the kind value.
     */
    public Kind kind() {
        return this.kind;
    }

    /**
     * Set the kind property: Indicates the type of scheduled query rule. The default is LogAlert.
     * 
     * @param kind the kind value to set.
     * @return the LogAlertRuleResource object itself.
     */
    public LogAlertRuleResource withKind(Kind kind) {
        this.kind = kind;
        return this;
    }

    /**
     * Get the innerProperties property: The rule properties of the resource.
     * 
     * @return the innerProperties value.
     */
    private LogAlertRuleProperties innerProperties() {
        return this.innerProperties;
    }

    /**
     * Get the description property: The description of the scheduled query rule.
     * 
     * @return the description value.
     */
    public String description() {
        return this.innerProperties() == null ? null : this.innerProperties().description();
    }

    /**
     * Set the description property: The description of the scheduled query rule.
     * 
     * @param description the description value to set.
     * @return the LogAlertRuleResource object itself.
     */
    public LogAlertRuleResource withDescription(String description) {
        if (this.innerProperties() == null) {
            this.innerProperties = new LogAlertRuleProperties();
        }
        this.innerProperties().withDescription(description);
        return this;
    }

    /**
     * Get the displayName property: The display name of the alert rule.
     * 
     * @return the displayName value.
     */
    public String displayName() {
        return this.innerProperties() == null ? null : this.innerProperties().displayName();
    }

    /**
     * Set the displayName property: The display name of the alert rule.
     * 
     * @param displayName the displayName value to set.
     * @return the LogAlertRuleResource object itself.
     */
    public LogAlertRuleResource withDisplayName(String displayName) {
        if (this.innerProperties() == null) {
            this.innerProperties = new LogAlertRuleProperties();
        }
        this.innerProperties().withDisplayName(displayName);
        return this;
    }

    /**
     * Get the severity property: Severity of the alert. Should be an integer between [0-4]. Value of 0 is severest.
     * Relevant and required only for rules of the kind LogAlert.
     * 
     * @return the severity value.
     */
    public AlertSeverity severity() {
        return this.innerProperties() == null ? null : this.innerProperties().severity();
    }

    /**
     * Set the severity property: Severity of the alert. Should be an integer between [0-4]. Value of 0 is severest.
     * Relevant and required only for rules of the kind LogAlert.
     * 
     * @param severity the severity value to set.
     * @return the LogAlertRuleResource object itself.
     */
    public LogAlertRuleResource withSeverity(AlertSeverity severity) {
        if (this.innerProperties() == null) {
            this.innerProperties = new LogAlertRuleProperties();
        }
        this.innerProperties().withSeverity(severity);
        return this;
    }

    /**
     * Get the enabled property: The flag which indicates whether this scheduled query rule is enabled. Value should be
     * true or false.
     * 
     * @return the enabled value.
     */
    public Boolean enabled() {
        return this.innerProperties() == null ? null : this.innerProperties().enabled();
    }

    /**
     * Set the enabled property: The flag which indicates whether this scheduled query rule is enabled. Value should be
     * true or false.
     * 
     * @param enabled the enabled value to set.
     * @return the LogAlertRuleResource object itself.
     */
    public LogAlertRuleResource withEnabled(Boolean enabled) {
        if (this.innerProperties() == null) {
            this.innerProperties = new LogAlertRuleProperties();
        }
        this.innerProperties().withEnabled(enabled);
        return this;
    }

    /**
     * Get the scopes property: The list of resource id's that this scheduled query rule is scoped to.
     * 
     * @return the scopes value.
     */
    public List<String> scopes() {
        return this.innerProperties() == null ? null : this.innerProperties().scopes();
    }

    /**
     * Set the scopes property: The list of resource id's that this scheduled query rule is scoped to.
     * 
     * @param scopes the scopes value to set.
     * @return the LogAlertRuleResource object itself.
     */
    public LogAlertRuleResource withScopes(List<String> scopes) {
        if (this.innerProperties() == null) {
            this.innerProperties = new LogAlertRuleProperties();
        }
        this.innerProperties().withScopes(scopes);
        return this;
    }

    /**
     * Get the evaluationFrequency property: How often the scheduled query rule is evaluated represented in ISO 8601
     * duration format. Relevant and required only for rules of the kind LogAlert.
     * 
     * @return the evaluationFrequency value.
     */
    public Duration evaluationFrequency() {
        return this.innerProperties() == null ? null : this.innerProperties().evaluationFrequency();
    }

    /**
     * Set the evaluationFrequency property: How often the scheduled query rule is evaluated represented in ISO 8601
     * duration format. Relevant and required only for rules of the kind LogAlert.
     * 
     * @param evaluationFrequency the evaluationFrequency value to set.
     * @return the LogAlertRuleResource object itself.
     */
    public LogAlertRuleResource withEvaluationFrequency(Duration evaluationFrequency) {
        if (this.innerProperties() == null) {
            this.innerProperties = new LogAlertRuleProperties();
        }
        this.innerProperties().withEvaluationFrequency(evaluationFrequency);
        return this;
    }

    /**
     * Get the windowSize property: The period of time (in ISO 8601 duration format) on which the Alert query will be
     * executed (bin size). Relevant and required only for rules of the kind LogAlert.
     * 
     * @return the windowSize value.
     */
    public Duration windowSize() {
        return this.innerProperties() == null ? null : this.innerProperties().windowSize();
    }

    /**
     * Set the windowSize property: The period of time (in ISO 8601 duration format) on which the Alert query will be
     * executed (bin size). Relevant and required only for rules of the kind LogAlert.
     * 
     * @param windowSize the windowSize value to set.
     * @return the LogAlertRuleResource object itself.
     */
    public LogAlertRuleResource withWindowSize(Duration windowSize) {
        if (this.innerProperties() == null) {
            this.innerProperties = new LogAlertRuleProperties();
        }
        this.innerProperties().withWindowSize(windowSize);
        return this;
    }

    /**
     * Get the overrideQueryTimeRange property: If specified then overrides the query time range (default is
     * WindowSize*NumberOfEvaluationPeriods). Relevant only for rules of the kind LogAlert.
     * 
     * @return the overrideQueryTimeRange value.
     */
    public Duration overrideQueryTimeRange() {
        return this.innerProperties() == null ? null : this.innerProperties().overrideQueryTimeRange();
    }

    /**
     * Set the overrideQueryTimeRange property: If specified then overrides the query time range (default is
     * WindowSize*NumberOfEvaluationPeriods). Relevant only for rules of the kind LogAlert.
     * 
     * @param overrideQueryTimeRange the overrideQueryTimeRange value to set.
     * @return the LogAlertRuleResource object itself.
     */
    public LogAlertRuleResource withOverrideQueryTimeRange(Duration overrideQueryTimeRange) {
        if (this.innerProperties() == null) {
            this.innerProperties = new LogAlertRuleProperties();
        }
        this.innerProperties().withOverrideQueryTimeRange(overrideQueryTimeRange);
        return this;
    }

    /**
     * Get the targetResourceTypes property: List of resource type of the target resource(s) on which the alert is
     * created/updated. For example if the scope is a resource group and targetResourceTypes is
     * Microsoft.Compute/virtualMachines, then a different alert will be fired for each virtual machine in the resource
     * group which meet the alert criteria. Relevant only for rules of the kind LogAlert.
     * 
     * @return the targetResourceTypes value.
     */
    public List<String> targetResourceTypes() {
        return this.innerProperties() == null ? null : this.innerProperties().targetResourceTypes();
    }

    /**
     * Set the targetResourceTypes property: List of resource type of the target resource(s) on which the alert is
     * created/updated. For example if the scope is a resource group and targetResourceTypes is
     * Microsoft.Compute/virtualMachines, then a different alert will be fired for each virtual machine in the resource
     * group which meet the alert criteria. Relevant only for rules of the kind LogAlert.
     * 
     * @param targetResourceTypes the targetResourceTypes value to set.
     * @return the LogAlertRuleResource object itself.
     */
    public LogAlertRuleResource withTargetResourceTypes(List<String> targetResourceTypes) {
        if (this.innerProperties() == null) {
            this.innerProperties = new LogAlertRuleProperties();
        }
        this.innerProperties().withTargetResourceTypes(targetResourceTypes);
        return this;
    }

    /**
     * Get the criteria property: The rule criteria that defines the conditions of the scheduled query rule.
     * 
     * @return the criteria value.
     */
    public LogAlertRuleCriteria criteria() {
        return this.innerProperties() == null ? null : this.innerProperties().criteria();
    }

    /**
     * Set the criteria property: The rule criteria that defines the conditions of the scheduled query rule.
     * 
     * @param criteria the criteria value to set.
     * @return the LogAlertRuleResource object itself.
     */
    public LogAlertRuleResource withCriteria(LogAlertRuleCriteria criteria) {
        if (this.innerProperties() == null) {
            this.innerProperties = new LogAlertRuleProperties();
        }
        this.innerProperties().withCriteria(criteria);
        return this;
    }

    /**
     * Validates the instance.
     * 
     * @throws IllegalArgumentException thrown if the instance is not valid.
     */
    public void validate() {
        if (location() == null) {
            throw LOGGER.atError()
                .log(new IllegalArgumentException("Missing required property location in model LogAlertRuleResource"));
        }
        if (innerProperties() == null) {
            throw LOGGER.atError()
                .log(new IllegalArgumentException(
                    "Missing required property innerProperties in model LogAlertRuleResource"));
        } else {
            innerProperties().validate();
        }
    }

    private static final ClientLogger LOGGER = new ClientLogger(LogAlertRuleResource.class);

    /**
     * {@inheritDoc}
     */
    @Override
    public JsonWriter toJson(JsonWriter jsonWriter) throws IOException {
        jsonWriter.writeStartObject();
        jsonWriter.writeStringField("location", this.location);
        jsonWriter.writeJsonField("properties", this.innerProperties);
        jsonWriter.writeMapField("tags", this.tags, (writer, element) -> writer.writeString(element));
        jsonWriter.writeStringField("kind", this.kind == null ? null : this.kind.toString());
        return jsonWriter.writeEndObject();
    }

    /**
     * Reads an instance of LogAlertRuleResource from the JsonReader.
     * 
     * @param jsonReader The JsonReader being read.
     * @return An instance of LogAlertRuleResource if the JsonReader was pointing to an instance of it, or null if it
     * was pointing to JSON null.
     * @throws IllegalStateException If the deserialized JSON object was missing any required properties.
     * @throws IOException If an error occurs while reading the LogAlertRuleResource.
     */
    public static LogAlertRuleResource fromJson(JsonReader jsonReader) throws IOException {
        return jsonReader.readObject(reader -> {
            LogAlertRuleResource deserializedLogAlertRuleResource = new LogAlertRuleResource();
            while (reader.nextToken() != JsonToken.END_OBJECT) {
                String fieldName = reader.getFieldName();
                reader.nextToken();

                if ("location".equals(fieldName)) {
                    deserializedLogAlertRuleResource.location = reader.getString();
                } else if ("properties".equals(fieldName)) {
                    deserializedLogAlertRuleResource.innerProperties = LogAlertRuleProperties.fromJson(reader);
                } else if ("tags".equals(fieldName)) {
                    Map<String, String> tags = reader.readMap(reader1 -> reader1.getString());
                    deserializedLogAlertRuleResource.tags = tags;
                } else if ("kind".equals(fieldName)) {
                    deserializedLogAlertRuleResource.kind = Kind.fromString(reader.getString());
                } else {
                    reader.skipChildren();
                }
            }

            return deserializedLogAlertRuleResource;
        });
    }
}
