// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.app.models;

import com.azure.core.annotation.Fluent;
import com.azure.json.JsonReader;
import com.azure.json.JsonSerializable;
import com.azure.json.JsonToken;
import com.azure.json.JsonWriter;
import java.io.IOException;
import java.util.List;

/**
 * The rule criteria that defines the conditions of the scheduled query rule.
 */
@Fluent
public final class LogAlertRuleCriteria implements JsonSerializable<LogAlertRuleCriteria> {
    /*
     * A list of conditions to evaluate against the specified scopes
     */
    private List<LogAlertRuleCondition> allOf;

    /**
     * Creates an instance of LogAlertRuleCriteria class.
     */
    public LogAlertRuleCriteria() {
    }

    /**
     * Get the allOf property: A list of conditions to evaluate against the specified scopes.
     * 
     * @return the allOf value.
     */
    public List<LogAlertRuleCondition> allOf() {
        return this.allOf;
    }

    /**
     * Set the allOf property: A list of conditions to evaluate against the specified scopes.
     * 
     * @param allOf the allOf value to set.
     * @return the LogAlertRuleCriteria object itself.
     */
    public LogAlertRuleCriteria withAllOf(List<LogAlertRuleCondition> allOf) {
        this.allOf = allOf;
        return this;
    }

    /**
     * Validates the instance.
     * 
     * @throws IllegalArgumentException thrown if the instance is not valid.
     */
    public void validate() {
        if (allOf() != null) {
            allOf().forEach(e -> e.validate());
        }
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public JsonWriter toJson(JsonWriter jsonWriter) throws IOException {
        jsonWriter.writeStartObject();
        jsonWriter.writeArrayField("allOf", this.allOf, (writer, element) -> writer.writeJson(element));
        return jsonWriter.writeEndObject();
    }

    /**
     * Reads an instance of LogAlertRuleCriteria from the JsonReader.
     * 
     * @param jsonReader The JsonReader being read.
     * @return An instance of LogAlertRuleCriteria if the JsonReader was pointing to an instance of it, or null if it
     * was pointing to JSON null.
     * @throws IOException If an error occurs while reading the LogAlertRuleCriteria.
     */
    public static LogAlertRuleCriteria fromJson(JsonReader jsonReader) throws IOException {
        return jsonReader.readObject(reader -> {
            LogAlertRuleCriteria deserializedLogAlertRuleCriteria = new LogAlertRuleCriteria();
            while (reader.nextToken() != JsonToken.END_OBJECT) {
                String fieldName = reader.getFieldName();
                reader.nextToken();

                if ("allOf".equals(fieldName)) {
                    List<LogAlertRuleCondition> allOf
                        = reader.readArray(reader1 -> LogAlertRuleCondition.fromJson(reader1));
                    deserializedLogAlertRuleCriteria.allOf = allOf;
                } else {
                    reader.skipChildren();
                }
            }

            return deserializedLogAlertRuleCriteria;
        });
    }
}
