// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.app.models;

import com.azure.app.fluent.models.PreviewAlertRuleResponseInner;
import java.util.List;

/**
 * An immutable client-side representation of PreviewAlertRuleResponse.
 */
public interface PreviewAlertRuleResponse {
    /**
     * Gets the rulePreviewResults property: An array of rule preview results.
     * 
     * @return the rulePreviewResults value.
     */
    List<RulePreviewResult> rulePreviewResults();

    /**
     * Gets the inner com.azure.app.fluent.models.PreviewAlertRuleResponseInner object.
     * 
     * @return the inner object.
     */
    PreviewAlertRuleResponseInner innerModel();
}
