// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.app.models;

import com.azure.core.annotation.Fluent;
import com.azure.core.util.CoreUtils;
import com.azure.core.util.logging.ClientLogger;
import com.azure.json.JsonReader;
import com.azure.json.JsonSerializable;
import com.azure.json.JsonToken;
import com.azure.json.JsonWriter;
import java.io.IOException;
import java.time.Duration;

/**
 * The PreviewAlertRuleRequestProperties model.
 */
@Fluent
public final class PreviewAlertRuleRequestProperties implements JsonSerializable<PreviewAlertRuleRequestProperties> {
    /*
     * Specifies the timespan of the preview in ISO 8601 duration format.
     */
    private Duration timespan;

    /*
     * The properties of the alert rule to preview.
     */
    private LogAlertRuleResource scheduledQueryRuleProperties;

    /**
     * Creates an instance of PreviewAlertRuleRequestProperties class.
     */
    public PreviewAlertRuleRequestProperties() {
    }

    /**
     * Get the timespan property: Specifies the timespan of the preview in ISO 8601 duration format.
     * 
     * @return the timespan value.
     */
    public Duration timespan() {
        return this.timespan;
    }

    /**
     * Set the timespan property: Specifies the timespan of the preview in ISO 8601 duration format.
     * 
     * @param timespan the timespan value to set.
     * @return the PreviewAlertRuleRequestProperties object itself.
     */
    public PreviewAlertRuleRequestProperties withTimespan(Duration timespan) {
        this.timespan = timespan;
        return this;
    }

    /**
     * Get the scheduledQueryRuleProperties property: The properties of the alert rule to preview.
     * 
     * @return the scheduledQueryRuleProperties value.
     */
    public LogAlertRuleResource scheduledQueryRuleProperties() {
        return this.scheduledQueryRuleProperties;
    }

    /**
     * Set the scheduledQueryRuleProperties property: The properties of the alert rule to preview.
     * 
     * @param scheduledQueryRuleProperties the scheduledQueryRuleProperties value to set.
     * @return the PreviewAlertRuleRequestProperties object itself.
     */
    public PreviewAlertRuleRequestProperties
        withScheduledQueryRuleProperties(LogAlertRuleResource scheduledQueryRuleProperties) {
        this.scheduledQueryRuleProperties = scheduledQueryRuleProperties;
        return this;
    }

    /**
     * Validates the instance.
     * 
     * @throws IllegalArgumentException thrown if the instance is not valid.
     */
    public void validate() {
        if (timespan() == null) {
            throw LOGGER.atError()
                .log(new IllegalArgumentException(
                    "Missing required property timespan in model PreviewAlertRuleRequestProperties"));
        }
        if (scheduledQueryRuleProperties() != null) {
            scheduledQueryRuleProperties().validate();
        }
    }

    private static final ClientLogger LOGGER = new ClientLogger(PreviewAlertRuleRequestProperties.class);

    /**
     * {@inheritDoc}
     */
    @Override
    public JsonWriter toJson(JsonWriter jsonWriter) throws IOException {
        jsonWriter.writeStartObject();
        jsonWriter.writeStringField("timespan", CoreUtils.durationToStringWithDays(this.timespan));
        jsonWriter.writeJsonField("scheduledQueryRuleProperties", this.scheduledQueryRuleProperties);
        return jsonWriter.writeEndObject();
    }

    /**
     * Reads an instance of PreviewAlertRuleRequestProperties from the JsonReader.
     * 
     * @param jsonReader The JsonReader being read.
     * @return An instance of PreviewAlertRuleRequestProperties if the JsonReader was pointing to an instance of it, or
     * null if it was pointing to JSON null.
     * @throws IllegalStateException If the deserialized JSON object was missing any required properties.
     * @throws IOException If an error occurs while reading the PreviewAlertRuleRequestProperties.
     */
    public static PreviewAlertRuleRequestProperties fromJson(JsonReader jsonReader) throws IOException {
        return jsonReader.readObject(reader -> {
            PreviewAlertRuleRequestProperties deserializedPreviewAlertRuleRequestProperties
                = new PreviewAlertRuleRequestProperties();
            while (reader.nextToken() != JsonToken.END_OBJECT) {
                String fieldName = reader.getFieldName();
                reader.nextToken();

                if ("timespan".equals(fieldName)) {
                    deserializedPreviewAlertRuleRequestProperties.timespan
                        = reader.getNullable(nonNullReader -> Duration.parse(nonNullReader.getString()));
                } else if ("scheduledQueryRuleProperties".equals(fieldName)) {
                    deserializedPreviewAlertRuleRequestProperties.scheduledQueryRuleProperties
                        = LogAlertRuleResource.fromJson(reader);
                } else {
                    reader.skipChildren();
                }
            }

            return deserializedPreviewAlertRuleRequestProperties;
        });
    }
}
