// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.app.models;

import com.azure.core.annotation.Fluent;
import com.azure.core.util.logging.ClientLogger;
import com.azure.json.JsonReader;
import com.azure.json.JsonSerializable;
import com.azure.json.JsonToken;
import com.azure.json.JsonWriter;
import java.io.IOException;

/**
 * The PreviewAlertRuleRequest model.
 */
@Fluent
public final class PreviewAlertRuleRequest implements JsonSerializable<PreviewAlertRuleRequest> {
    /*
     * The location of the rule resource.
     */
    private String location;

    /*
     * The properties property.
     */
    private PreviewAlertRuleRequestProperties properties;

    /**
     * Creates an instance of PreviewAlertRuleRequest class.
     */
    public PreviewAlertRuleRequest() {
    }

    /**
     * Get the location property: The location of the rule resource.
     * 
     * @return the location value.
     */
    public String location() {
        return this.location;
    }

    /**
     * Set the location property: The location of the rule resource.
     * 
     * @param location the location value to set.
     * @return the PreviewAlertRuleRequest object itself.
     */
    public PreviewAlertRuleRequest withLocation(String location) {
        this.location = location;
        return this;
    }

    /**
     * Get the properties property: The properties property.
     * 
     * @return the properties value.
     */
    public PreviewAlertRuleRequestProperties properties() {
        return this.properties;
    }

    /**
     * Set the properties property: The properties property.
     * 
     * @param properties the properties value to set.
     * @return the PreviewAlertRuleRequest object itself.
     */
    public PreviewAlertRuleRequest withProperties(PreviewAlertRuleRequestProperties properties) {
        this.properties = properties;
        return this;
    }

    /**
     * Validates the instance.
     * 
     * @throws IllegalArgumentException thrown if the instance is not valid.
     */
    public void validate() {
        if (location() == null) {
            throw LOGGER.atError()
                .log(new IllegalArgumentException(
                    "Missing required property location in model PreviewAlertRuleRequest"));
        }
        if (properties() == null) {
            throw LOGGER.atError()
                .log(new IllegalArgumentException(
                    "Missing required property properties in model PreviewAlertRuleRequest"));
        } else {
            properties().validate();
        }
    }

    private static final ClientLogger LOGGER = new ClientLogger(PreviewAlertRuleRequest.class);

    /**
     * {@inheritDoc}
     */
    @Override
    public JsonWriter toJson(JsonWriter jsonWriter) throws IOException {
        jsonWriter.writeStartObject();
        jsonWriter.writeStringField("location", this.location);
        jsonWriter.writeJsonField("properties", this.properties);
        return jsonWriter.writeEndObject();
    }

    /**
     * Reads an instance of PreviewAlertRuleRequest from the JsonReader.
     * 
     * @param jsonReader The JsonReader being read.
     * @return An instance of PreviewAlertRuleRequest if the JsonReader was pointing to an instance of it, or null if it
     * was pointing to JSON null.
     * @throws IllegalStateException If the deserialized JSON object was missing any required properties.
     * @throws IOException If an error occurs while reading the PreviewAlertRuleRequest.
     */
    public static PreviewAlertRuleRequest fromJson(JsonReader jsonReader) throws IOException {
        return jsonReader.readObject(reader -> {
            PreviewAlertRuleRequest deserializedPreviewAlertRuleRequest = new PreviewAlertRuleRequest();
            while (reader.nextToken() != JsonToken.END_OBJECT) {
                String fieldName = reader.getFieldName();
                reader.nextToken();

                if ("location".equals(fieldName)) {
                    deserializedPreviewAlertRuleRequest.location = reader.getString();
                } else if ("properties".equals(fieldName)) {
                    deserializedPreviewAlertRuleRequest.properties = PreviewAlertRuleRequestProperties.fromJson(reader);
                } else {
                    reader.skipChildren();
                }
            }

            return deserializedPreviewAlertRuleRequest;
        });
    }
}
