// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.app.models;

import com.azure.core.annotation.Fluent;
import com.azure.json.JsonReader;
import com.azure.json.JsonSerializable;
import com.azure.json.JsonToken;
import com.azure.json.JsonWriter;
import java.io.IOException;
import java.util.List;

/**
 * A rule preview result containing a dimension combination and an array of evaluations.
 */
@Fluent
public final class RulePreviewResult implements JsonSerializable<RulePreviewResult> {
    /*
     * The list of dimensions for the evaluation.
     */
    private List<DimensionNameAndValue> dimensionCombination;

    /*
     * An array of evaluations.
     */
    private List<Evaluation> evaluations;

    /**
     * Creates an instance of RulePreviewResult class.
     */
    public RulePreviewResult() {
    }

    /**
     * Get the dimensionCombination property: The list of dimensions for the evaluation.
     * 
     * @return the dimensionCombination value.
     */
    public List<DimensionNameAndValue> dimensionCombination() {
        return this.dimensionCombination;
    }

    /**
     * Set the dimensionCombination property: The list of dimensions for the evaluation.
     * 
     * @param dimensionCombination the dimensionCombination value to set.
     * @return the RulePreviewResult object itself.
     */
    public RulePreviewResult withDimensionCombination(List<DimensionNameAndValue> dimensionCombination) {
        this.dimensionCombination = dimensionCombination;
        return this;
    }

    /**
     * Get the evaluations property: An array of evaluations.
     * 
     * @return the evaluations value.
     */
    public List<Evaluation> evaluations() {
        return this.evaluations;
    }

    /**
     * Set the evaluations property: An array of evaluations.
     * 
     * @param evaluations the evaluations value to set.
     * @return the RulePreviewResult object itself.
     */
    public RulePreviewResult withEvaluations(List<Evaluation> evaluations) {
        this.evaluations = evaluations;
        return this;
    }

    /**
     * Validates the instance.
     * 
     * @throws IllegalArgumentException thrown if the instance is not valid.
     */
    public void validate() {
        if (dimensionCombination() != null) {
            dimensionCombination().forEach(e -> e.validate());
        }
        if (evaluations() != null) {
            evaluations().forEach(e -> e.validate());
        }
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public JsonWriter toJson(JsonWriter jsonWriter) throws IOException {
        jsonWriter.writeStartObject();
        jsonWriter.writeArrayField("dimensionCombination", this.dimensionCombination,
            (writer, element) -> writer.writeJson(element));
        jsonWriter.writeArrayField("evaluations", this.evaluations, (writer, element) -> writer.writeJson(element));
        return jsonWriter.writeEndObject();
    }

    /**
     * Reads an instance of RulePreviewResult from the JsonReader.
     * 
     * @param jsonReader The JsonReader being read.
     * @return An instance of RulePreviewResult if the JsonReader was pointing to an instance of it, or null if it was
     * pointing to JSON null.
     * @throws IOException If an error occurs while reading the RulePreviewResult.
     */
    public static RulePreviewResult fromJson(JsonReader jsonReader) throws IOException {
        return jsonReader.readObject(reader -> {
            RulePreviewResult deserializedRulePreviewResult = new RulePreviewResult();
            while (reader.nextToken() != JsonToken.END_OBJECT) {
                String fieldName = reader.getFieldName();
                reader.nextToken();

                if ("dimensionCombination".equals(fieldName)) {
                    List<DimensionNameAndValue> dimensionCombination
                        = reader.readArray(reader1 -> DimensionNameAndValue.fromJson(reader1));
                    deserializedRulePreviewResult.dimensionCombination = dimensionCombination;
                } else if ("evaluations".equals(fieldName)) {
                    List<Evaluation> evaluations = reader.readArray(reader1 -> Evaluation.fromJson(reader1));
                    deserializedRulePreviewResult.evaluations = evaluations;
                } else {
                    reader.skipChildren();
                }
            }

            return deserializedRulePreviewResult;
        });
    }
}
