// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

/**
 * Package containing the classes for PreviewAlertRuleApiInAlertsManagementServiceResourceProvider.
 * The Preview Alert Rule API provides the ability to retrieve the results of a simulated historical execution of an
 * alert rule.
 */
package com.azure.app;
