// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

/**
 * Package containing the service clients for AzureAlertsManagementServiceResourceProvider.
 * Azure Alerts Management Service provides a single pane of glass of alerts across Azure Monitor.
 */
package com.azure.app.fluent;
