// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.app.implementation;

import com.azure.app.fluent.models.AlertRuleRecommendationResourceInner;
import com.azure.app.models.AlertRuleRecommendationResource;
import com.azure.app.models.RuleArmTemplate;
import com.azure.core.management.SystemData;
import java.util.Collections;
import java.util.Map;

public final class AlertRuleRecommendationResourceImpl implements AlertRuleRecommendationResource {
    private AlertRuleRecommendationResourceInner innerObject;

    private final com.azure.app.AppManager serviceManager;

    AlertRuleRecommendationResourceImpl(AlertRuleRecommendationResourceInner innerObject,
        com.azure.app.AppManager serviceManager) {
        this.innerObject = innerObject;
        this.serviceManager = serviceManager;
    }

    public String id() {
        return this.innerModel().id();
    }

    public String name() {
        return this.innerModel().name();
    }

    public String type() {
        return this.innerModel().type();
    }

    public SystemData systemData() {
        return this.innerModel().systemData();
    }

    public String alertRuleType() {
        return this.innerModel().alertRuleType();
    }

    public String category() {
        return this.innerModel().category();
    }

    public Map<String, String> displayInformation() {
        Map<String, String> inner = this.innerModel().displayInformation();
        if (inner != null) {
            return Collections.unmodifiableMap(inner);
        } else {
            return Collections.emptyMap();
        }
    }

    public RuleArmTemplate ruleArmTemplate() {
        return this.innerModel().ruleArmTemplate();
    }

    public AlertRuleRecommendationResourceInner innerModel() {
        return this.innerObject;
    }

    private com.azure.app.AppManager manager() {
        return this.serviceManager;
    }
}
