// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.app.implementation;

import com.azure.app.fluent.AlertRuleRecommendationsClient;
import com.azure.app.fluent.models.AlertRuleRecommendationResourceInner;
import com.azure.app.models.AlertRuleRecommendationResource;
import com.azure.app.models.AlertRuleRecommendations;
import com.azure.core.http.rest.PagedIterable;
import com.azure.core.util.Context;
import com.azure.core.util.logging.ClientLogger;

public final class AlertRuleRecommendationsImpl implements AlertRuleRecommendations {
    private static final ClientLogger LOGGER = new ClientLogger(AlertRuleRecommendationsImpl.class);

    private final AlertRuleRecommendationsClient innerClient;

    private final com.azure.app.AppManager serviceManager;

    public AlertRuleRecommendationsImpl(AlertRuleRecommendationsClient innerClient,
        com.azure.app.AppManager serviceManager) {
        this.innerClient = innerClient;
        this.serviceManager = serviceManager;
    }

    public PagedIterable<AlertRuleRecommendationResource> listByResource(String resourceUri) {
        PagedIterable<AlertRuleRecommendationResourceInner> inner = this.serviceClient().listByResource(resourceUri);
        return ResourceManagerUtils.mapPage(inner,
            inner1 -> new AlertRuleRecommendationResourceImpl(inner1, this.manager()));
    }

    public PagedIterable<AlertRuleRecommendationResource> listByResource(String resourceUri, Context context) {
        PagedIterable<AlertRuleRecommendationResourceInner> inner
            = this.serviceClient().listByResource(resourceUri, context);
        return ResourceManagerUtils.mapPage(inner,
            inner1 -> new AlertRuleRecommendationResourceImpl(inner1, this.manager()));
    }

    public PagedIterable<AlertRuleRecommendationResource> list(String targetType) {
        PagedIterable<AlertRuleRecommendationResourceInner> inner = this.serviceClient().list(targetType);
        return ResourceManagerUtils.mapPage(inner,
            inner1 -> new AlertRuleRecommendationResourceImpl(inner1, this.manager()));
    }

    public PagedIterable<AlertRuleRecommendationResource> list(String targetType, Context context) {
        PagedIterable<AlertRuleRecommendationResourceInner> inner = this.serviceClient().list(targetType, context);
        return ResourceManagerUtils.mapPage(inner,
            inner1 -> new AlertRuleRecommendationResourceImpl(inner1, this.manager()));
    }

    private AlertRuleRecommendationsClient serviceClient() {
        return this.innerClient;
    }

    private com.azure.app.AppManager manager() {
        return this.serviceManager;
    }
}
