// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.app.implementation;

import com.azure.app.fluent.models.PreviewAlertRuleResponseInner;
import com.azure.app.models.PreviewAlertRuleResponse;
import com.azure.app.models.RulePreviewResult;
import java.util.Collections;
import java.util.List;

public final class PreviewAlertRuleResponseImpl implements PreviewAlertRuleResponse {
    private PreviewAlertRuleResponseInner innerObject;

    private final com.azure.app.AppManager serviceManager;

    PreviewAlertRuleResponseImpl(PreviewAlertRuleResponseInner innerObject, com.azure.app.AppManager serviceManager) {
        this.innerObject = innerObject;
        this.serviceManager = serviceManager;
    }

    public List<RulePreviewResult> rulePreviewResults() {
        List<RulePreviewResult> inner = this.innerModel().rulePreviewResults();
        if (inner != null) {
            return Collections.unmodifiableList(inner);
        } else {
            return Collections.emptyList();
        }
    }

    public PreviewAlertRuleResponseInner innerModel() {
        return this.innerObject;
    }

    private com.azure.app.AppManager manager() {
        return this.serviceManager;
    }
}
