// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.app.implementation;

import com.azure.app.fluent.ResourceProvidersClient;
import com.azure.app.fluent.models.PreviewAlertRuleResponseInner;
import com.azure.app.models.PreviewAlertRuleRequest;
import com.azure.app.models.PreviewAlertRuleResponse;
import com.azure.app.models.ResourceProviders;
import com.azure.core.http.rest.Response;
import com.azure.core.http.rest.SimpleResponse;
import com.azure.core.util.Context;
import com.azure.core.util.logging.ClientLogger;

public final class ResourceProvidersImpl implements ResourceProviders {
    private static final ClientLogger LOGGER = new ClientLogger(ResourceProvidersImpl.class);

    private final ResourceProvidersClient innerClient;

    private final com.azure.app.AppManager serviceManager;

    public ResourceProvidersImpl(ResourceProvidersClient innerClient, com.azure.app.AppManager serviceManager) {
        this.innerClient = innerClient;
        this.serviceManager = serviceManager;
    }

    public Response<PreviewAlertRuleResponse> previewAlertRuleWithResponse(String resourceId,
        PreviewAlertRuleRequest parameters, Context context) {
        Response<PreviewAlertRuleResponseInner> inner
            = this.serviceClient().previewAlertRuleWithResponse(resourceId, parameters, context);
        if (inner != null) {
            return new SimpleResponse<>(inner.getRequest(), inner.getStatusCode(), inner.getHeaders(),
                new PreviewAlertRuleResponseImpl(inner.getValue(), this.manager()));
        } else {
            return null;
        }
    }

    public PreviewAlertRuleResponse previewAlertRule(String resourceId, PreviewAlertRuleRequest parameters) {
        PreviewAlertRuleResponseInner inner = this.serviceClient().previewAlertRule(resourceId, parameters);
        if (inner != null) {
            return new PreviewAlertRuleResponseImpl(inner, this.manager());
        } else {
            return null;
        }
    }

    private ResourceProvidersClient serviceClient() {
        return this.innerClient;
    }

    private com.azure.app.AppManager manager() {
        return this.serviceManager;
    }
}
