// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.app.implementation;

import com.azure.app.fluent.models.TenantActivityLogAlertResourceInner;
import com.azure.app.models.ActionList;
import com.azure.app.models.AlertRuleAllOfCondition;
import com.azure.app.models.TenantActivityLogAlertResource;
import java.util.Collections;
import java.util.List;
import java.util.Map;

public final class TenantActivityLogAlertResourceImpl implements TenantActivityLogAlertResource {
    private TenantActivityLogAlertResourceInner innerObject;

    private final com.azure.app.AppManager serviceManager;

    TenantActivityLogAlertResourceImpl(TenantActivityLogAlertResourceInner innerObject,
        com.azure.app.AppManager serviceManager) {
        this.innerObject = innerObject;
        this.serviceManager = serviceManager;
    }

    public String id() {
        return this.innerModel().id();
    }

    public String name() {
        return this.innerModel().name();
    }

    public String type() {
        return this.innerModel().type();
    }

    public String location() {
        return this.innerModel().location();
    }

    public Map<String, String> tags() {
        Map<String, String> inner = this.innerModel().tags();
        if (inner != null) {
            return Collections.unmodifiableMap(inner);
        } else {
            return Collections.emptyMap();
        }
    }

    public String tenantScope() {
        return this.innerModel().tenantScope();
    }

    public List<String> scopes() {
        List<String> inner = this.innerModel().scopes();
        if (inner != null) {
            return Collections.unmodifiableList(inner);
        } else {
            return Collections.emptyList();
        }
    }

    public AlertRuleAllOfCondition condition() {
        return this.innerModel().condition();
    }

    public ActionList actions() {
        return this.innerModel().actions();
    }

    public Boolean enabled() {
        return this.innerModel().enabled();
    }

    public String description() {
        return this.innerModel().description();
    }

    public TenantActivityLogAlertResourceInner innerModel() {
        return this.innerObject;
    }

    private com.azure.app.AppManager manager() {
        return this.serviceManager;
    }
}
