// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.app.fluent.models;

import com.azure.app.models.AlertSeverity;
import com.azure.app.models.LogAlertRuleCriteria;
import com.azure.core.annotation.Fluent;
import com.azure.core.util.CoreUtils;
import com.azure.json.JsonReader;
import com.azure.json.JsonSerializable;
import com.azure.json.JsonToken;
import com.azure.json.JsonWriter;
import java.io.IOException;
import java.time.Duration;
import java.util.List;

/**
 * scheduled query rule Definition.
 */
@Fluent
public final class LogAlertRuleProperties implements JsonSerializable<LogAlertRuleProperties> {
    /*
     * The description of the scheduled query rule.
     */
    private String description;

    /*
     * The display name of the alert rule
     */
    private String displayName;

    /*
     * Severity of the alert. Should be an integer between [0-4]. Value of 0 is severest. Relevant and required only for
     * rules of the kind LogAlert.
     */
    private AlertSeverity severity;

    /*
     * The flag which indicates whether this scheduled query rule is enabled. Value should be true or false
     */
    private Boolean enabled;

    /*
     * The list of resource id's that this scheduled query rule is scoped to.
     */
    private List<String> scopes;

    /*
     * How often the scheduled query rule is evaluated represented in ISO 8601 duration format. Relevant and required
     * only for rules of the kind LogAlert.
     */
    private Duration evaluationFrequency;

    /*
     * The period of time (in ISO 8601 duration format) on which the Alert query will be executed (bin size). Relevant
     * and required only for rules of the kind LogAlert.
     */
    private Duration windowSize;

    /*
     * If specified then overrides the query time range (default is WindowSize*NumberOfEvaluationPeriods). Relevant only
     * for rules of the kind LogAlert.
     */
    private Duration overrideQueryTimeRange;

    /*
     * List of resource type of the target resource(s) on which the alert is created/updated. For example if the scope
     * is a resource group and targetResourceTypes is Microsoft.Compute/virtualMachines, then a different alert will be
     * fired for each virtual machine in the resource group which meet the alert criteria. Relevant only for rules of
     * the kind LogAlert
     */
    private List<String> targetResourceTypes;

    /*
     * The rule criteria that defines the conditions of the scheduled query rule.
     */
    private LogAlertRuleCriteria criteria;

    /**
     * Creates an instance of LogAlertRuleProperties class.
     */
    public LogAlertRuleProperties() {
    }

    /**
     * Get the description property: The description of the scheduled query rule.
     * 
     * @return the description value.
     */
    public String description() {
        return this.description;
    }

    /**
     * Set the description property: The description of the scheduled query rule.
     * 
     * @param description the description value to set.
     * @return the LogAlertRuleProperties object itself.
     */
    public LogAlertRuleProperties withDescription(String description) {
        this.description = description;
        return this;
    }

    /**
     * Get the displayName property: The display name of the alert rule.
     * 
     * @return the displayName value.
     */
    public String displayName() {
        return this.displayName;
    }

    /**
     * Set the displayName property: The display name of the alert rule.
     * 
     * @param displayName the displayName value to set.
     * @return the LogAlertRuleProperties object itself.
     */
    public LogAlertRuleProperties withDisplayName(String displayName) {
        this.displayName = displayName;
        return this;
    }

    /**
     * Get the severity property: Severity of the alert. Should be an integer between [0-4]. Value of 0 is severest.
     * Relevant and required only for rules of the kind LogAlert.
     * 
     * @return the severity value.
     */
    public AlertSeverity severity() {
        return this.severity;
    }

    /**
     * Set the severity property: Severity of the alert. Should be an integer between [0-4]. Value of 0 is severest.
     * Relevant and required only for rules of the kind LogAlert.
     * 
     * @param severity the severity value to set.
     * @return the LogAlertRuleProperties object itself.
     */
    public LogAlertRuleProperties withSeverity(AlertSeverity severity) {
        this.severity = severity;
        return this;
    }

    /**
     * Get the enabled property: The flag which indicates whether this scheduled query rule is enabled. Value should be
     * true or false.
     * 
     * @return the enabled value.
     */
    public Boolean enabled() {
        return this.enabled;
    }

    /**
     * Set the enabled property: The flag which indicates whether this scheduled query rule is enabled. Value should be
     * true or false.
     * 
     * @param enabled the enabled value to set.
     * @return the LogAlertRuleProperties object itself.
     */
    public LogAlertRuleProperties withEnabled(Boolean enabled) {
        this.enabled = enabled;
        return this;
    }

    /**
     * Get the scopes property: The list of resource id's that this scheduled query rule is scoped to.
     * 
     * @return the scopes value.
     */
    public List<String> scopes() {
        return this.scopes;
    }

    /**
     * Set the scopes property: The list of resource id's that this scheduled query rule is scoped to.
     * 
     * @param scopes the scopes value to set.
     * @return the LogAlertRuleProperties object itself.
     */
    public LogAlertRuleProperties withScopes(List<String> scopes) {
        this.scopes = scopes;
        return this;
    }

    /**
     * Get the evaluationFrequency property: How often the scheduled query rule is evaluated represented in ISO 8601
     * duration format. Relevant and required only for rules of the kind LogAlert.
     * 
     * @return the evaluationFrequency value.
     */
    public Duration evaluationFrequency() {
        return this.evaluationFrequency;
    }

    /**
     * Set the evaluationFrequency property: How often the scheduled query rule is evaluated represented in ISO 8601
     * duration format. Relevant and required only for rules of the kind LogAlert.
     * 
     * @param evaluationFrequency the evaluationFrequency value to set.
     * @return the LogAlertRuleProperties object itself.
     */
    public LogAlertRuleProperties withEvaluationFrequency(Duration evaluationFrequency) {
        this.evaluationFrequency = evaluationFrequency;
        return this;
    }

    /**
     * Get the windowSize property: The period of time (in ISO 8601 duration format) on which the Alert query will be
     * executed (bin size). Relevant and required only for rules of the kind LogAlert.
     * 
     * @return the windowSize value.
     */
    public Duration windowSize() {
        return this.windowSize;
    }

    /**
     * Set the windowSize property: The period of time (in ISO 8601 duration format) on which the Alert query will be
     * executed (bin size). Relevant and required only for rules of the kind LogAlert.
     * 
     * @param windowSize the windowSize value to set.
     * @return the LogAlertRuleProperties object itself.
     */
    public LogAlertRuleProperties withWindowSize(Duration windowSize) {
        this.windowSize = windowSize;
        return this;
    }

    /**
     * Get the overrideQueryTimeRange property: If specified then overrides the query time range (default is
     * WindowSize*NumberOfEvaluationPeriods). Relevant only for rules of the kind LogAlert.
     * 
     * @return the overrideQueryTimeRange value.
     */
    public Duration overrideQueryTimeRange() {
        return this.overrideQueryTimeRange;
    }

    /**
     * Set the overrideQueryTimeRange property: If specified then overrides the query time range (default is
     * WindowSize*NumberOfEvaluationPeriods). Relevant only for rules of the kind LogAlert.
     * 
     * @param overrideQueryTimeRange the overrideQueryTimeRange value to set.
     * @return the LogAlertRuleProperties object itself.
     */
    public LogAlertRuleProperties withOverrideQueryTimeRange(Duration overrideQueryTimeRange) {
        this.overrideQueryTimeRange = overrideQueryTimeRange;
        return this;
    }

    /**
     * Get the targetResourceTypes property: List of resource type of the target resource(s) on which the alert is
     * created/updated. For example if the scope is a resource group and targetResourceTypes is
     * Microsoft.Compute/virtualMachines, then a different alert will be fired for each virtual machine in the resource
     * group which meet the alert criteria. Relevant only for rules of the kind LogAlert.
     * 
     * @return the targetResourceTypes value.
     */
    public List<String> targetResourceTypes() {
        return this.targetResourceTypes;
    }

    /**
     * Set the targetResourceTypes property: List of resource type of the target resource(s) on which the alert is
     * created/updated. For example if the scope is a resource group and targetResourceTypes is
     * Microsoft.Compute/virtualMachines, then a different alert will be fired for each virtual machine in the resource
     * group which meet the alert criteria. Relevant only for rules of the kind LogAlert.
     * 
     * @param targetResourceTypes the targetResourceTypes value to set.
     * @return the LogAlertRuleProperties object itself.
     */
    public LogAlertRuleProperties withTargetResourceTypes(List<String> targetResourceTypes) {
        this.targetResourceTypes = targetResourceTypes;
        return this;
    }

    /**
     * Get the criteria property: The rule criteria that defines the conditions of the scheduled query rule.
     * 
     * @return the criteria value.
     */
    public LogAlertRuleCriteria criteria() {
        return this.criteria;
    }

    /**
     * Set the criteria property: The rule criteria that defines the conditions of the scheduled query rule.
     * 
     * @param criteria the criteria value to set.
     * @return the LogAlertRuleProperties object itself.
     */
    public LogAlertRuleProperties withCriteria(LogAlertRuleCriteria criteria) {
        this.criteria = criteria;
        return this;
    }

    /**
     * Validates the instance.
     * 
     * @throws IllegalArgumentException thrown if the instance is not valid.
     */
    public void validate() {
        if (criteria() != null) {
            criteria().validate();
        }
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public JsonWriter toJson(JsonWriter jsonWriter) throws IOException {
        jsonWriter.writeStartObject();
        jsonWriter.writeStringField("description", this.description);
        jsonWriter.writeStringField("displayName", this.displayName);
        jsonWriter.writeNumberField("severity", this.severity == null ? null : this.severity.getValue());
        jsonWriter.writeBooleanField("enabled", this.enabled);
        jsonWriter.writeArrayField("scopes", this.scopes, (writer, element) -> writer.writeString(element));
        jsonWriter.writeStringField("evaluationFrequency",
            CoreUtils.durationToStringWithDays(this.evaluationFrequency));
        jsonWriter.writeStringField("windowSize", CoreUtils.durationToStringWithDays(this.windowSize));
        jsonWriter.writeStringField("overrideQueryTimeRange",
            CoreUtils.durationToStringWithDays(this.overrideQueryTimeRange));
        jsonWriter.writeArrayField("targetResourceTypes", this.targetResourceTypes,
            (writer, element) -> writer.writeString(element));
        jsonWriter.writeJsonField("criteria", this.criteria);
        return jsonWriter.writeEndObject();
    }

    /**
     * Reads an instance of LogAlertRuleProperties from the JsonReader.
     * 
     * @param jsonReader The JsonReader being read.
     * @return An instance of LogAlertRuleProperties if the JsonReader was pointing to an instance of it, or null if it
     * was pointing to JSON null.
     * @throws IOException If an error occurs while reading the LogAlertRuleProperties.
     */
    public static LogAlertRuleProperties fromJson(JsonReader jsonReader) throws IOException {
        return jsonReader.readObject(reader -> {
            LogAlertRuleProperties deserializedLogAlertRuleProperties = new LogAlertRuleProperties();
            while (reader.nextToken() != JsonToken.END_OBJECT) {
                String fieldName = reader.getFieldName();
                reader.nextToken();

                if ("description".equals(fieldName)) {
                    deserializedLogAlertRuleProperties.description = reader.getString();
                } else if ("displayName".equals(fieldName)) {
                    deserializedLogAlertRuleProperties.displayName = reader.getString();
                } else if ("severity".equals(fieldName)) {
                    deserializedLogAlertRuleProperties.severity = AlertSeverity.fromValue(reader.getFloat());
                } else if ("enabled".equals(fieldName)) {
                    deserializedLogAlertRuleProperties.enabled = reader.getNullable(JsonReader::getBoolean);
                } else if ("scopes".equals(fieldName)) {
                    List<String> scopes = reader.readArray(reader1 -> reader1.getString());
                    deserializedLogAlertRuleProperties.scopes = scopes;
                } else if ("evaluationFrequency".equals(fieldName)) {
                    deserializedLogAlertRuleProperties.evaluationFrequency
                        = reader.getNullable(nonNullReader -> Duration.parse(nonNullReader.getString()));
                } else if ("windowSize".equals(fieldName)) {
                    deserializedLogAlertRuleProperties.windowSize
                        = reader.getNullable(nonNullReader -> Duration.parse(nonNullReader.getString()));
                } else if ("overrideQueryTimeRange".equals(fieldName)) {
                    deserializedLogAlertRuleProperties.overrideQueryTimeRange
                        = reader.getNullable(nonNullReader -> Duration.parse(nonNullReader.getString()));
                } else if ("targetResourceTypes".equals(fieldName)) {
                    List<String> targetResourceTypes = reader.readArray(reader1 -> reader1.getString());
                    deserializedLogAlertRuleProperties.targetResourceTypes = targetResourceTypes;
                } else if ("criteria".equals(fieldName)) {
                    deserializedLogAlertRuleProperties.criteria = LogAlertRuleCriteria.fromJson(reader);
                } else {
                    reader.skipChildren();
                }
            }

            return deserializedLogAlertRuleProperties;
        });
    }
}
