// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.app.fluent.models;

import com.azure.app.models.RulePreviewResult;
import com.azure.core.annotation.Fluent;
import com.azure.json.JsonReader;
import com.azure.json.JsonSerializable;
import com.azure.json.JsonToken;
import com.azure.json.JsonWriter;
import java.io.IOException;
import java.util.List;

/**
 * The PreviewAlertRuleResponse model.
 */
@Fluent
public final class PreviewAlertRuleResponseInner implements JsonSerializable<PreviewAlertRuleResponseInner> {
    /*
     * An array of rule preview results.
     */
    private List<RulePreviewResult> rulePreviewResults;

    /**
     * Creates an instance of PreviewAlertRuleResponseInner class.
     */
    public PreviewAlertRuleResponseInner() {
    }

    /**
     * Get the rulePreviewResults property: An array of rule preview results.
     * 
     * @return the rulePreviewResults value.
     */
    public List<RulePreviewResult> rulePreviewResults() {
        return this.rulePreviewResults;
    }

    /**
     * Set the rulePreviewResults property: An array of rule preview results.
     * 
     * @param rulePreviewResults the rulePreviewResults value to set.
     * @return the PreviewAlertRuleResponseInner object itself.
     */
    public PreviewAlertRuleResponseInner withRulePreviewResults(List<RulePreviewResult> rulePreviewResults) {
        this.rulePreviewResults = rulePreviewResults;
        return this;
    }

    /**
     * Validates the instance.
     * 
     * @throws IllegalArgumentException thrown if the instance is not valid.
     */
    public void validate() {
        if (rulePreviewResults() != null) {
            rulePreviewResults().forEach(e -> e.validate());
        }
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public JsonWriter toJson(JsonWriter jsonWriter) throws IOException {
        jsonWriter.writeStartObject();
        jsonWriter.writeArrayField("rulePreviewResults", this.rulePreviewResults,
            (writer, element) -> writer.writeJson(element));
        return jsonWriter.writeEndObject();
    }

    /**
     * Reads an instance of PreviewAlertRuleResponseInner from the JsonReader.
     * 
     * @param jsonReader The JsonReader being read.
     * @return An instance of PreviewAlertRuleResponseInner if the JsonReader was pointing to an instance of it, or null
     * if it was pointing to JSON null.
     * @throws IOException If an error occurs while reading the PreviewAlertRuleResponseInner.
     */
    public static PreviewAlertRuleResponseInner fromJson(JsonReader jsonReader) throws IOException {
        return jsonReader.readObject(reader -> {
            PreviewAlertRuleResponseInner deserializedPreviewAlertRuleResponseInner
                = new PreviewAlertRuleResponseInner();
            while (reader.nextToken() != JsonToken.END_OBJECT) {
                String fieldName = reader.getFieldName();
                reader.nextToken();

                if ("rulePreviewResults".equals(fieldName)) {
                    List<RulePreviewResult> rulePreviewResults
                        = reader.readArray(reader1 -> RulePreviewResult.fromJson(reader1));
                    deserializedPreviewAlertRuleResponseInner.rulePreviewResults = rulePreviewResults;
                } else {
                    reader.skipChildren();
                }
            }

            return deserializedPreviewAlertRuleResponseInner;
        });
    }
}
