// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.app.fluent.models;

import com.azure.app.models.PrometheusRule;
import com.azure.core.annotation.Fluent;
import com.azure.core.util.CoreUtils;
import com.azure.core.util.logging.ClientLogger;
import com.azure.json.JsonReader;
import com.azure.json.JsonSerializable;
import com.azure.json.JsonToken;
import com.azure.json.JsonWriter;
import java.io.IOException;
import java.time.Duration;
import java.util.List;

/**
 * An Azure Prometheus rule group.
 */
@Fluent
public final class PrometheusRuleGroupProperties implements JsonSerializable<PrometheusRuleGroupProperties> {
    /*
     * Rule group description.
     */
    private String description;

    /*
     * Enable/disable rule group.
     */
    private Boolean enabled;

    /*
     * Apply rule to data from a specific cluster.
     */
    private String clusterName;

    /*
     * Target Azure Monitor workspaces resource ids. This api-version is currently limited to creating with one scope.
     * This may change in future.
     */
    private List<String> scopes;

    /*
     * The interval in which to run the Prometheus rule group represented in ISO 8601 duration format. Should be between
     * 1 and 15 minutes
     */
    private Duration interval;

    /*
     * Defines the rules in the Prometheus rule group.
     */
    private List<PrometheusRule> rules;

    /**
     * Creates an instance of PrometheusRuleGroupProperties class.
     */
    public PrometheusRuleGroupProperties() {
    }

    /**
     * Get the description property: Rule group description.
     * 
     * @return the description value.
     */
    public String description() {
        return this.description;
    }

    /**
     * Set the description property: Rule group description.
     * 
     * @param description the description value to set.
     * @return the PrometheusRuleGroupProperties object itself.
     */
    public PrometheusRuleGroupProperties withDescription(String description) {
        this.description = description;
        return this;
    }

    /**
     * Get the enabled property: Enable/disable rule group.
     * 
     * @return the enabled value.
     */
    public Boolean enabled() {
        return this.enabled;
    }

    /**
     * Set the enabled property: Enable/disable rule group.
     * 
     * @param enabled the enabled value to set.
     * @return the PrometheusRuleGroupProperties object itself.
     */
    public PrometheusRuleGroupProperties withEnabled(Boolean enabled) {
        this.enabled = enabled;
        return this;
    }

    /**
     * Get the clusterName property: Apply rule to data from a specific cluster.
     * 
     * @return the clusterName value.
     */
    public String clusterName() {
        return this.clusterName;
    }

    /**
     * Set the clusterName property: Apply rule to data from a specific cluster.
     * 
     * @param clusterName the clusterName value to set.
     * @return the PrometheusRuleGroupProperties object itself.
     */
    public PrometheusRuleGroupProperties withClusterName(String clusterName) {
        this.clusterName = clusterName;
        return this;
    }

    /**
     * Get the scopes property: Target Azure Monitor workspaces resource ids. This api-version is currently limited to
     * creating with one scope. This may change in future.
     * 
     * @return the scopes value.
     */
    public List<String> scopes() {
        return this.scopes;
    }

    /**
     * Set the scopes property: Target Azure Monitor workspaces resource ids. This api-version is currently limited to
     * creating with one scope. This may change in future.
     * 
     * @param scopes the scopes value to set.
     * @return the PrometheusRuleGroupProperties object itself.
     */
    public PrometheusRuleGroupProperties withScopes(List<String> scopes) {
        this.scopes = scopes;
        return this;
    }

    /**
     * Get the interval property: The interval in which to run the Prometheus rule group represented in ISO 8601
     * duration format. Should be between 1 and 15 minutes.
     * 
     * @return the interval value.
     */
    public Duration interval() {
        return this.interval;
    }

    /**
     * Set the interval property: The interval in which to run the Prometheus rule group represented in ISO 8601
     * duration format. Should be between 1 and 15 minutes.
     * 
     * @param interval the interval value to set.
     * @return the PrometheusRuleGroupProperties object itself.
     */
    public PrometheusRuleGroupProperties withInterval(Duration interval) {
        this.interval = interval;
        return this;
    }

    /**
     * Get the rules property: Defines the rules in the Prometheus rule group.
     * 
     * @return the rules value.
     */
    public List<PrometheusRule> rules() {
        return this.rules;
    }

    /**
     * Set the rules property: Defines the rules in the Prometheus rule group.
     * 
     * @param rules the rules value to set.
     * @return the PrometheusRuleGroupProperties object itself.
     */
    public PrometheusRuleGroupProperties withRules(List<PrometheusRule> rules) {
        this.rules = rules;
        return this;
    }

    /**
     * Validates the instance.
     * 
     * @throws IllegalArgumentException thrown if the instance is not valid.
     */
    public void validate() {
        if (scopes() == null) {
            throw LOGGER.atError()
                .log(new IllegalArgumentException(
                    "Missing required property scopes in model PrometheusRuleGroupProperties"));
        }
        if (rules() == null) {
            throw LOGGER.atError()
                .log(new IllegalArgumentException(
                    "Missing required property rules in model PrometheusRuleGroupProperties"));
        } else {
            rules().forEach(e -> e.validate());
        }
    }

    private static final ClientLogger LOGGER = new ClientLogger(PrometheusRuleGroupProperties.class);

    /**
     * {@inheritDoc}
     */
    @Override
    public JsonWriter toJson(JsonWriter jsonWriter) throws IOException {
        jsonWriter.writeStartObject();
        jsonWriter.writeArrayField("scopes", this.scopes, (writer, element) -> writer.writeString(element));
        jsonWriter.writeArrayField("rules", this.rules, (writer, element) -> writer.writeJson(element));
        jsonWriter.writeStringField("description", this.description);
        jsonWriter.writeBooleanField("enabled", this.enabled);
        jsonWriter.writeStringField("clusterName", this.clusterName);
        jsonWriter.writeStringField("interval", CoreUtils.durationToStringWithDays(this.interval));
        return jsonWriter.writeEndObject();
    }

    /**
     * Reads an instance of PrometheusRuleGroupProperties from the JsonReader.
     * 
     * @param jsonReader The JsonReader being read.
     * @return An instance of PrometheusRuleGroupProperties if the JsonReader was pointing to an instance of it, or null
     * if it was pointing to JSON null.
     * @throws IllegalStateException If the deserialized JSON object was missing any required properties.
     * @throws IOException If an error occurs while reading the PrometheusRuleGroupProperties.
     */
    public static PrometheusRuleGroupProperties fromJson(JsonReader jsonReader) throws IOException {
        return jsonReader.readObject(reader -> {
            PrometheusRuleGroupProperties deserializedPrometheusRuleGroupProperties
                = new PrometheusRuleGroupProperties();
            while (reader.nextToken() != JsonToken.END_OBJECT) {
                String fieldName = reader.getFieldName();
                reader.nextToken();

                if ("scopes".equals(fieldName)) {
                    List<String> scopes = reader.readArray(reader1 -> reader1.getString());
                    deserializedPrometheusRuleGroupProperties.scopes = scopes;
                } else if ("rules".equals(fieldName)) {
                    List<PrometheusRule> rules = reader.readArray(reader1 -> PrometheusRule.fromJson(reader1));
                    deserializedPrometheusRuleGroupProperties.rules = rules;
                } else if ("description".equals(fieldName)) {
                    deserializedPrometheusRuleGroupProperties.description = reader.getString();
                } else if ("enabled".equals(fieldName)) {
                    deserializedPrometheusRuleGroupProperties.enabled = reader.getNullable(JsonReader::getBoolean);
                } else if ("clusterName".equals(fieldName)) {
                    deserializedPrometheusRuleGroupProperties.clusterName = reader.getString();
                } else if ("interval".equals(fieldName)) {
                    deserializedPrometheusRuleGroupProperties.interval
                        = reader.getNullable(nonNullReader -> Duration.parse(nonNullReader.getString()));
                } else {
                    reader.skipChildren();
                }
            }

            return deserializedPrometheusRuleGroupProperties;
        });
    }
}
