// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.app.models;

import com.azure.app.fluent.models.PrometheusRuleGroupResourcePatchParametersProperties;
import com.azure.core.annotation.Fluent;
import com.azure.json.JsonReader;
import com.azure.json.JsonSerializable;
import com.azure.json.JsonToken;
import com.azure.json.JsonWriter;
import java.io.IOException;
import java.util.Map;

/**
 * The Prometheus rule group resource for patch operations.
 */
@Fluent
public final class PrometheusRuleGroupResourcePatchParameters
    implements JsonSerializable<PrometheusRuleGroupResourcePatchParameters> {
    /*
     * Resource tags
     */
    private Map<String, String> tags;

    /*
     * The properties property.
     */
    private PrometheusRuleGroupResourcePatchParametersProperties innerProperties;

    /**
     * Creates an instance of PrometheusRuleGroupResourcePatchParameters class.
     */
    public PrometheusRuleGroupResourcePatchParameters() {
    }

    /**
     * Get the tags property: Resource tags.
     * 
     * @return the tags value.
     */
    public Map<String, String> tags() {
        return this.tags;
    }

    /**
     * Set the tags property: Resource tags.
     * 
     * @param tags the tags value to set.
     * @return the PrometheusRuleGroupResourcePatchParameters object itself.
     */
    public PrometheusRuleGroupResourcePatchParameters withTags(Map<String, String> tags) {
        this.tags = tags;
        return this;
    }

    /**
     * Get the innerProperties property: The properties property.
     * 
     * @return the innerProperties value.
     */
    private PrometheusRuleGroupResourcePatchParametersProperties innerProperties() {
        return this.innerProperties;
    }

    /**
     * Get the enabled property: the flag that indicates whether the Prometheus rule group is enabled.
     * 
     * @return the enabled value.
     */
    public Boolean enabled() {
        return this.innerProperties() == null ? null : this.innerProperties().enabled();
    }

    /**
     * Set the enabled property: the flag that indicates whether the Prometheus rule group is enabled.
     * 
     * @param enabled the enabled value to set.
     * @return the PrometheusRuleGroupResourcePatchParameters object itself.
     */
    public PrometheusRuleGroupResourcePatchParameters withEnabled(Boolean enabled) {
        if (this.innerProperties() == null) {
            this.innerProperties = new PrometheusRuleGroupResourcePatchParametersProperties();
        }
        this.innerProperties().withEnabled(enabled);
        return this;
    }

    /**
     * Validates the instance.
     * 
     * @throws IllegalArgumentException thrown if the instance is not valid.
     */
    public void validate() {
        if (innerProperties() != null) {
            innerProperties().validate();
        }
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public JsonWriter toJson(JsonWriter jsonWriter) throws IOException {
        jsonWriter.writeStartObject();
        jsonWriter.writeMapField("tags", this.tags, (writer, element) -> writer.writeString(element));
        jsonWriter.writeJsonField("properties", this.innerProperties);
        return jsonWriter.writeEndObject();
    }

    /**
     * Reads an instance of PrometheusRuleGroupResourcePatchParameters from the JsonReader.
     * 
     * @param jsonReader The JsonReader being read.
     * @return An instance of PrometheusRuleGroupResourcePatchParameters if the JsonReader was pointing to an instance
     * of it, or null if it was pointing to JSON null.
     * @throws IOException If an error occurs while reading the PrometheusRuleGroupResourcePatchParameters.
     */
    public static PrometheusRuleGroupResourcePatchParameters fromJson(JsonReader jsonReader) throws IOException {
        return jsonReader.readObject(reader -> {
            PrometheusRuleGroupResourcePatchParameters deserializedPrometheusRuleGroupResourcePatchParameters
                = new PrometheusRuleGroupResourcePatchParameters();
            while (reader.nextToken() != JsonToken.END_OBJECT) {
                String fieldName = reader.getFieldName();
                reader.nextToken();

                if ("tags".equals(fieldName)) {
                    Map<String, String> tags = reader.readMap(reader1 -> reader1.getString());
                    deserializedPrometheusRuleGroupResourcePatchParameters.tags = tags;
                } else if ("properties".equals(fieldName)) {
                    deserializedPrometheusRuleGroupResourcePatchParameters.innerProperties
                        = PrometheusRuleGroupResourcePatchParametersProperties.fromJson(reader);
                } else {
                    reader.skipChildren();
                }
            }

            return deserializedPrometheusRuleGroupResourcePatchParameters;
        });
    }
}
