// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.app.models;

import com.azure.core.annotation.Fluent;
import com.azure.core.util.CoreUtils;
import com.azure.json.JsonReader;
import com.azure.json.JsonSerializable;
import com.azure.json.JsonToken;
import com.azure.json.JsonWriter;
import java.io.IOException;
import java.time.Duration;

/**
 * Specifies the Prometheus alert rule configuration.
 */
@Fluent
public final class PrometheusRuleResolveConfiguration implements JsonSerializable<PrometheusRuleResolveConfiguration> {
    /*
     * Enable alert auto-resolution.
     */
    private Boolean autoResolved;

    /*
     * Alert auto-resolution timeout.
     */
    private Duration timeToResolve;

    /**
     * Creates an instance of PrometheusRuleResolveConfiguration class.
     */
    public PrometheusRuleResolveConfiguration() {
    }

    /**
     * Get the autoResolved property: Enable alert auto-resolution.
     * 
     * @return the autoResolved value.
     */
    public Boolean autoResolved() {
        return this.autoResolved;
    }

    /**
     * Set the autoResolved property: Enable alert auto-resolution.
     * 
     * @param autoResolved the autoResolved value to set.
     * @return the PrometheusRuleResolveConfiguration object itself.
     */
    public PrometheusRuleResolveConfiguration withAutoResolved(Boolean autoResolved) {
        this.autoResolved = autoResolved;
        return this;
    }

    /**
     * Get the timeToResolve property: Alert auto-resolution timeout.
     * 
     * @return the timeToResolve value.
     */
    public Duration timeToResolve() {
        return this.timeToResolve;
    }

    /**
     * Set the timeToResolve property: Alert auto-resolution timeout.
     * 
     * @param timeToResolve the timeToResolve value to set.
     * @return the PrometheusRuleResolveConfiguration object itself.
     */
    public PrometheusRuleResolveConfiguration withTimeToResolve(Duration timeToResolve) {
        this.timeToResolve = timeToResolve;
        return this;
    }

    /**
     * Validates the instance.
     * 
     * @throws IllegalArgumentException thrown if the instance is not valid.
     */
    public void validate() {
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public JsonWriter toJson(JsonWriter jsonWriter) throws IOException {
        jsonWriter.writeStartObject();
        jsonWriter.writeBooleanField("autoResolved", this.autoResolved);
        jsonWriter.writeStringField("timeToResolve", CoreUtils.durationToStringWithDays(this.timeToResolve));
        return jsonWriter.writeEndObject();
    }

    /**
     * Reads an instance of PrometheusRuleResolveConfiguration from the JsonReader.
     * 
     * @param jsonReader The JsonReader being read.
     * @return An instance of PrometheusRuleResolveConfiguration if the JsonReader was pointing to an instance of it, or
     * null if it was pointing to JSON null.
     * @throws IOException If an error occurs while reading the PrometheusRuleResolveConfiguration.
     */
    public static PrometheusRuleResolveConfiguration fromJson(JsonReader jsonReader) throws IOException {
        return jsonReader.readObject(reader -> {
            PrometheusRuleResolveConfiguration deserializedPrometheusRuleResolveConfiguration
                = new PrometheusRuleResolveConfiguration();
            while (reader.nextToken() != JsonToken.END_OBJECT) {
                String fieldName = reader.getFieldName();
                reader.nextToken();

                if ("autoResolved".equals(fieldName)) {
                    deserializedPrometheusRuleResolveConfiguration.autoResolved
                        = reader.getNullable(JsonReader::getBoolean);
                } else if ("timeToResolve".equals(fieldName)) {
                    deserializedPrometheusRuleResolveConfiguration.timeToResolve
                        = reader.getNullable(nonNullReader -> Duration.parse(nonNullReader.getString()));
                } else {
                    reader.skipChildren();
                }
            }

            return deserializedPrometheusRuleResolveConfiguration;
        });
    }
}
